#include <bits/stdc++.h>

#include <atcoder/all>

#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int64_t N, M, C;
  cin >> N >> M >> C;
  map<int64_t, int64_t> A;
  REP(i, N) {
    int64_t a;
    cin >> a;
    A[a]++;
  }

  if (A.size() == 1) {
    int64_t dist = M;
    int64_t ans = dist * A.begin()->second;
    cout << ans << endl;
    return 0;
  }

  int64_t ans = 0;
  int64_t tmp = 0;
  auto start = A.begin();
  auto it = start;
  while (start != A.end()) {
    tmp += it->second;
    while (tmp >= C) {
      auto prev = [&]() {
        if (start == A.begin()) {
          // loop back
          auto last = A.end();
          --last;
          return last;
        } else {
          return std::prev(start);
        }
      }();
      auto dist = (start->first - prev->first + M) % M;
      ans += tmp * dist;
      // shift start iterator and remove start counts
      tmp -= start->second;
      ++start;
    }
    ++it;
    if (it == A.end()) {
      // loop back
      it = A.begin();
    }
  }

  cout << ans << endl;

  return 0;
}
