#include <bits/stdc++.h>

#include <atcoder/all>

#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int64_t N, M, C;
  cin >> N >> M >> C;
  map<int64_t, int64_t> A;
  REP(i, N) {
    int64_t a;
    cin >> a;
    A[a]++;
  }

  int64_t ans = 0;
  int64_t tmp = 0;
  auto start = A.begin();
  auto prev_pos = A.rbegin()->first - M;
  auto it = start;
  while (start != A.end()) {
    while (tmp < C) {
      tmp += it->second;
      ++it;
      if (it == A.end()) {
        // loop back
        it = A.begin();
      }
    }
    auto dist = (start->first - prev_pos);
    ans += tmp * dist;
    // shift start iterator and remove start counts
    prev_pos = start->first;
    tmp -= start->second;
    ++start;
  }

  cout << ans << endl;

  return 0;
}
