#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

void solve(void) {
  int N, M;
  cin >> N >> M;
  vector<int> A(N);
  for (auto& a : A) {
    cin >> a;
  }
  sort(ALL(A));
  vector<int> B(N);
  for (auto& b : B) {
    cin >> b;
  }
  sort(ALL(B));
  reverse(ALL(B));

  int ans = 0;
  int i = 0;
  vector<bool> used(N, false);
  bool loop = false;
  for (int j = 0; j < N; ++j) {
    while (!loop) {
      auto mod = (A[i] + B[j]) >= M;
      if (mod) {
        break;
      }
      i++;
      if (i >= N) {
        loop = true;
        i = 0;
        break;
      }
    }

    while (used[i]) {
      i++;
    }
    auto mod = (A[i] + B[j]) % M;
    ans += mod;
    used[i] = true;
    i++;
  }

  cout << ans << "\n";
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int64_t T;
  cin >> T;
  REP(i, T) { solve(); }

  return 0;
}
