#include <bits/stdc++.h>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int64_t R;
  cin >> R;
  R *= 2;
  double R2 = R * R;

  int64_t ans = 0;

  // Operate quater circle
  // Circle formula
  // x^2 + y^2 = r^2
  // y = sqrt(x^2 + r^2)
  double tmp_y = 1.0;
  while (tmp_y < R) {
    auto max_x = sqrt(R2 - (tmp_y * tmp_y));
    ans += static_cast<int64_t>((max_x - 1) / 2);
    tmp_y += 2.0;
  }

  // Add remain circle without center
  ans *= 4;
  // Add Center
  ans++;

  cout << ans << endl;
  return 0;
}
