#include <bits/stdc++.h>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int R;
  cin >> R;
  double R2 = R * R;

  int ans = 0;

  // Operate quater circle
  // Circle formula
  // x^2 + y^2 = r^2
  // y = sqrt(x^2 + r^2)
  double tmp_y = -R + 0.5;
  while (tmp_y < R) {
    auto max_x = sqrt(R2 - (tmp_y * tmp_y));
    auto len_x = static_cast<int>(max_x + 0.5) * 2;
    ans += (len_x < 1) ? 0 : len_x - 1;
    tmp_y += 1.0;
  }

  cout << ans << endl;
  return 0;
}
