#include <bits/stdc++.h>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int R;
  cin >> R;
  R *= 2;
  double R2 = R * R;

  int ans = 0;

  // Operate quater circle
  // Circle formula
  // x^2 + y^2 = r^2
  // y = sqrt(x^2 + r^2)
  double tmp_y = 1;
  auto max_x = sqrt(R2 - (tmp_y * tmp_y));
  auto num_on_axis = max_x / 2;
  ans += num_on_axis;
  tmp_y += 2.0;
  while (tmp_y < R) {
    auto max_x = sqrt(R2 - (tmp_y * tmp_y));
    ans += static_cast<int>(max_x + 0.5);
    tmp_y += 2.0;
  }

  // add remain circle without center
  ans *= 4;
  // Remove Duplication
  // Center
  ans -= 3;
  // axis
  ans -= (num_on_axis - 1) * 4;

  cout << ans << endl;
  return 0;
}
