#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  // failed to analyze input format
  // TODO: edit here
  int Q;
  std::cin >> Q;
  queue<int> q;
  REP(i, Q) {
    int query;
    std::cin >> query;
    if (query == 1) {
      int X;
      cin >> X;
      q.emplace(X);
    } else {
      auto ans = q.front();
      q.pop();
      cout << ans << "\n";
    }
  }
  return 0;
}
