#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  string S;
  cin >> S;
  string T;
  cin >> T;

  auto f = [](string& str) {
    vector<int> cnts{0};
    string s;
    for (char c : str) {
      if (c == 'A') {
        cnts.back()++;
      } else {
        cnts.push_back(0);
        s += c;
      }
    }
    return make_pair(cnts, s);
  };

  auto [S_cnt, s] = f(S);
  auto [T_cnt, t] = f(T);

  if (s != t) {
    // cannot solve
    cout << -1 << endl;
    return 0;
  }

  int size = max(S_cnt.size(), T_cnt.size());
  int ans = 0;
  REP(i, size) {
    int s_cnt = (i < S_cnt.size()) ? S_cnt[i] : 0;
    int t_cnt = (i < T_cnt.size()) ? T_cnt[i] : 0;
    ans += abs(s_cnt - t_cnt);
  }

  cout << ans << endl;
  return 0;
}
