#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  string S;
  cin >> S;
  string T;
  cin >> T;

  int64_t i = 0;
  int64_t ans = 0;
  for (auto c : T) {
    if (c == 'A') {
      if (i < S.size() && S[i] == 'A') {
        // do nothing
        i++;
      } else {
        // insert 'A'
        ans++;
      }
    } else {
      while (i < S.size() && S[i] == 'A') {
        // remove 'A'
        ans++;
        i++;
      }

      if (i >= S.size() || S[i] != c) {
        // cannot solve
        cout << -1 << endl;
        return 0;
      }
      i++;
    }
  }
  while (i < S.size() && S[i] == 'A') {
    // remove 'A'
    ans++;
    i++;
  }

  // Remain other 'A' char
  if (i < S.size()) {
    // cannot solve
    cout << -1 << endl;
    return 0;
  }

  cout << ans << endl;
  return 0;
}
