#include <bits/stdc++.h>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N, K;
  cin >> N >> K;

  string S;
  cin >> S;

  int ans = 0;
  int count = 0;
  for (auto s : S) {
    if (s == 'O') {
      count++;
    } else {
      count = 0;
    }

    if (count >= K) {
      ans++;
      count -= K;
    }
  }

  cout << ans << endl;

  return 0;
}
