#include <bits/stdc++.h>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N, K;
  cin >> N >> K;

  string S;
  cin >> S;

  int ans = 0;
  string expected = string(K, 'O');
  string replace = string(K, 'X');
  for (int i = 0; i < N - K + 1; i++) {
    if (S.substr(i, K) == expected) {
      ans++;
      S.replace(i, K, replace);
    }
  }

  cout << ans << endl;

  return 0;
}
