#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  string S;
  cin >> S;
  int cnt = 0;
  vector<int> ans;
  REP(i, S.size()) {
    if (S[i] == '#') {
      ans.push_back(i + 1);
      cnt++;
      if (cnt == 2) {
        cout << ans[0] << ',' << ans[1] << '\n';
        ans.clear();
        cnt = 0;
      }
    }
  }

  return 0;
}
