#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N, K, X;
  cin >> N >> K >> X;

  vector<string> S(N);
  for (auto &s : S) {
    cin >> s;
  }

  vector<string> dict;
  if (K == 1) {
    REP(i, N) { dict.push_back(S[i]); }
    sort(ALL(dict));
    cout << S[X - 1] << '\n';
    return 0;
  }

  stack<pair<string, int>> st;
  REP(i, N) { st.emplace(S[i], 1); }
  while (!st.empty()) {
    auto [s, k] = st.top();
    st.pop();
    k++;
    REP(i, N) {
      auto next_s = s + S[i];
      if (k == K) {
        dict.push_back(next_s);
      } else {
        st.emplace(next_s, k);
      }
    }
  }
  sort(ALL(dict));

  std::cout << dict[X - 1] << '\n';
  return 0;
}
