#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

const std::string YES = "Yes";
const std::string NO = "No";

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int64_t N, Q;
  cin >> N >> Q;
  vector<int64_t> pc_1(N);
  vector<string> pc_2(N);
  vector<string> server(1);
  REP(i, Q) {
    int64_t q, p;
    cin >> q >> p;
    p--;

    switch (q) {
      case 1: {
        pc_1[p] = server.size() - 1;
        pc_2[p] = "";
      } break;
      case 2: {
        string s;
        cin >> s;
        pc_2[p] += s;
      } break;
      case 3: {
        server.push_back(server[pc_1[p]] + pc_2[p]);
      } break;
      default:
        break;
    }
  }

  cout << server.back() << endl;

  return 0;
}
