#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

const std::string YES = "Yes";
const std::string NO = "No";

struct Query {
  int64_t type;
  int64_t p;
  string s;
};

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int64_t N, Q;
  cin >> N >> Q;

  vector<Query> queries(Q);
  REP(i, Q) {
    int64_t type, p;
    string s;
    cin >> type >> p;
    if (type == 2) {
      cin >> s;
    }
    queries[i] = {type, p, s};
  }

  int64_t pc = 0;
  vector<string> adds;
  // Reverse iteration
  reverse(ALL(queries));
  for (auto [type, p, s] : queries) {
    switch (type) {
      case 1: {
        // clear reference pc number
        if (p == pc) pc = 0;
      } break;
      case 2: {
        if (p == pc) {
          adds.push_back(s);
        }
      } break;
      case 3: {
        // Set reference pc number
        if (pc == 0) pc = p;
      } break;
      default:
        break;
    }
  }

  string ans;
  reverse(ALL(adds));
  for (const auto& add : adds) {
    ans += add;
  }

  cout << ans << endl;

  return 0;
}
