#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

bool judge(vector<int> A, int l) {
  while (!A.empty() && A.back() == l) {
    A.pop_back();
  }
  auto size = A.size();
  if (size % 2 != 0) {
    return false;
  }
  REP(i, size / 2) {
    if ((A[i] + A[size - 1 - i]) != l) {
      return false;
    }
  }
  return true;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N;
  cin >> N;

  vector<int> A(N);
  REP(i, N) { cin >> A[i]; }

  vector<int> ans(N, -1);
  queue<int> q;

  REP(i, N) {
    if (ans[i] != -1) {
      continue;
    }
    q.push(i);

    int next = A[i];
    while (next != A[next - 1]) {
      next = A[next - 1];
      q.push(next - 1);
    }

    while (!q.empty()) {
      auto idx = q.front();
      q.pop();
      ans[idx] = next;
    }
  }

  REP(i, N) { cout << ans[i] << " "; }
  cout << endl;
  return 0;
}
