#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  string S;
  cin >> S;

  REP(_, 1000000) {
    int64_t tmp = 0;
    for (char c : S) {
      int n = c - '0';
      tmp += n * n;
    }
    if (tmp == 1) {
      cout << "Yes" << endl;
      return 0;
    }
    S = to_string(tmp);
  }

  cout << "No" << endl;
  return 0;
}
