#include <bits/stdc++.h>

#include <atcoder/all>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)

void solve() {
  string A, B;
  cin >> A >> B;

  auto remove_brackets = [&](const string& S) -> string {
    string res;
    int cnt_x = 0;
    for (char c : S) {
      switch (c) {
        case '(': {
          res += string(cnt_x, 'x');
          cnt_x = 0;
          res += c;
        } break;
        case 'x':
          cnt_x++;
          break;
        case ')': {
          if (cnt_x == 2 && !res.empty() && res.back() == '(') {
            res.pop_back();
          } else {
            res += string(cnt_x, 'x');
            cnt_x = 0;
            res += c;
          }
        } break;

        default:
          break;
      }
    }
    if (cnt_x > 0) {
      res += string(cnt_x, 'x');
    }
    return res;
  };

  auto a = remove_brackets(A);
  auto b = remove_brackets(B);

  if (a == b) {
    cout << "Yes\n";
    return;
  } else {
    cout << "No\n";
  }
}

int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int T;
  cin >> T;
  REP(_, T) { solve(); }

  return 0;
}
