#include <bits/stdc++.h>

#include <atcoder/all>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)

void solve() {
  string A, B;
  cin >> A >> B;

  auto remove_brackets = [&](const string& S) -> string {
    string res;
    for (char c : S) {
      res += c;
      if (res.ends_with("(xx)")) {
        res.pop_back();
        res.pop_back();
        res.pop_back();
        res.pop_back();
        res += "xx";
      }
    }
    return res;
  };

  auto a = remove_brackets(A);
  auto b = remove_brackets(B);

  if (a == b) {
    cout << "Yes\n";
    return;
  } else {
    cout << "No\n";
  }
}

int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int T;
  cin >> T;
  REP(_, T) { solve(); }

  return 0;
}
