#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N, T, P;

  cin >> N >> T >> P;

  vector<int> L(N);
  for (auto& l : L) {
    cin >> l;
  }

  sort(L.rbegin(), L.rend());

  int ans = max(T - L[P - 1], 0);
  cout << ans << endl;

  return 0;
}
