#include <bits/stdc++.h>
using namespace std;

const string YES = "Yes";
const string NO = "No";

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N;
  cin >> N;

  auto str = to_string(N);

  int one = 0;
  int two = 0;
  int three = 0;
  for (auto s : str) {
    if (s == '1') one++;
    if (s == '2') two++;
    if (s == '3') three++;
  }

  if ((one == 1) && (two == 2) && (three == 3)) {
    cout << "Yes" << endl;
  } else {
    cout << "No" << endl;
  }

  return 0;
}
