#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

vector<int> solve(std::string S, std::string T) {
  vector<int> ans;
  int i = 0;
  for (auto s : S) {
    while (s != T[i]) {
      i++;
    }

    ans.emplace_back(i + 1);
    i++;
  }
  return ans;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  std::string S, T;
  std::cin >> S >> T;
  auto ans = solve(S, T);
  // failed to analyze output format
  for (auto a : ans) {
    std::cout << a << ' ';
  }
  std::cout << endl;
  return 0;
}
