#include <bits/stdc++.h>

#include <atcoder/all>

#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

// モノイド
bool op(bool a, bool b) { return false; }
// 単位元
bool e() { return false; }
using Act = bool;  // 区間反転するかどうか
// 作用関数
bool mapping(Act f, bool x) {
  if (f)
    return !x;
  else
    return x;
}
// 作用の合成関数
Act composition(Act g, bool f) {
  if (g) f = !f;
  return f;
}
// 作用の単位元
Act id() { return false; }

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N, M;
  cin >> N >> M;
  string S, T;
  cin >> S >> T;

  lazy_segtree<bool, op, e, bool, mapping, composition, id> seg(N);

  vector<pair<int, int>> P(M);
  for (auto& p : P) {
    int L, R;
    cin >> L >> R;
    p = {L - 1, R - 1};
    seg.apply(p.first, p.second + 1, true);
  }

  REP(i, N) {
    if (seg.get(i)) {
      cout << T[i];
    } else {
      cout << S[i];
    }
  }

  cout << '\n';

  return 0;
}
