#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

const std::string YES = "Yes";
const std::string NO = "No";
bool solve(int S, vector<int> T) {
  int prev = 0;
  for (auto t : T) {
    if ((t - prev) > S) {
      return false;
    }
    prev = t;
  }
  return true;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  int64_t N, S;
  std::cin >> N >> S;
  vector<int> T(N);
  REP(i, N) { cin >> T[i]; }
  auto ans = solve(S, T);
  std::cout << (ans ? YES : NO) << '\n';
  return 0;
}
