#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

const string YES = "Yes";
const string NO = "No";

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N;
  cin >> N;

  bool wasSweet = false;
  bool ill = false;
  bool result = true;
  for (int i = 0; i < N; i++) {
    if (ill) {
      result = false;
      break;
    }
    string s;
    cin >> s;
    bool isSweet = (s == "sweet");
    ill = wasSweet && isSweet;
    wasSweet = isSweet;
  }

  string ans = result ? YES : NO;

  cout << ans << endl;

  return 0;
}
