#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int64_t N, X, Y;
  cin >> N >> X >> Y;

  vector<int> A(N);
  REP(i, N) { cin >> A[i]; }
  sort(ALL(A));

  int64_t ans = A[0];
  int64_t diff = Y - X;
  for (int64_t i = 1; i < N; ++i) {
    int64_t dweight = (A[i] - A[0]) * Y;
    auto x = div(dweight, diff);
    if (x.rem != 0 || x.quot > A[i]) {
      cout << -1 << endl;
      return 0;
    }
    ans += A[i] - x.quot;
  }

  cout << ans << endl;
  return 0;
}
