#include <bits/stdc++.h>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N, R;
  cin >> N >> R;
  for (int i = 0; i < N; i++) {
    int D, A;
    cin >> D >> A;
    switch (D) {
      case 1:
        if (R >= 1600 && R <= 2799) {
          R += A;
        }
        break;
      default:
        if (R >= 1200 && R <= 2399) {
          R += A;
        }
        break;
    }
  }

  cout << R << endl;

  return 0;
}
