#include <bits/stdc++.h>

#include <atcoder/all>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int H, W, N;
  cin >> H >> W >> N;

  vector<pair<int, int>> A(N);
  REP(i, N) { cin >> A[i].first >> A[i].second; }

  vector<int> idx_h(N);
  iota(ALL(idx_h), 0);
  sort(ALL(idx_h), [&](int i, int j) { return A[i].first > A[j].first; });

  vector<int> idx_w(N);
  iota(ALL(idx_w), 0);
  sort(ALL(idx_w), [&](int i, int j) { return A[i].second > A[j].second; });

  vector<bool> idx_put(N, false);

  vector<pair<int, int>> ans(N);
  int idx_h_ptr = 0;
  auto idx_h_value = idx_h[idx_h_ptr];
  int idx_w_ptr = 0;
  auto idx_w_value = idx_w[idx_w_ptr];
  REP(i, N) {
    while (idx_put[idx_h_value]) {
      idx_h_ptr++;
      idx_h_value = idx_h[idx_h_ptr];
    }
    while (idx_put[idx_w_value]) {
      idx_w_ptr++;
      idx_w_value = idx_w[idx_w_ptr];
    }

    auto diff_h = H - A[idx_h_value].first;
    auto diff_w = W - A[idx_w_value].second;
    auto idx = (diff_h < diff_w) ? idx_h_value : idx_w_value;
    idx_put[idx] = true;
    auto [h, w] = A[idx];
    ans[idx] = {H - h + 1, W - w + 1};
    if (h == H) {
      W -= w;
    } else {
      H -= h;
    }
  }
  REP(i, N) { cout << ans[i].first << " " << ans[i].second << endl; }
  return 0;
}
