#include <bits/stdc++.h>

#include <atcoder/all>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int H, W, N;
  cin >> H >> W >> N;

  vector<pair<int, int>> A(N);
  REP(i, N) { cin >> A[i].first >> A[i].second; }

  unordered_map<int, vector<int>> map_h, map_w;
  REP(i, N) {
    map_h[A[i].first].push_back(i);
    map_w[A[i].second].push_back(i);
  }

  vector<bool> idx_put(N, false);
  vector<pair<int, int>> ans(N);
  auto get_idx = [&](unordered_map<int, vector<int>>& m, int val) {
    if (!m.contains(val)) {
      return -1;
    }

    auto& idxs = m[val];
    while (!idxs.empty() && idx_put[idxs.back()]) {
      idxs.pop_back();
    }
    if (idxs.empty()) {
      return -1;
    }
    return idxs.back();
  };
  REP(_, N) {
    auto idx = get_idx(map_h, H);
    if (idx == -1) {
      idx = get_idx(map_w, W);
    }
    auto [h, w] = A[idx];
    ans[idx] = {H - h + 1, W - w + 1};
    if (h == H) {
      W -= w;
    } else {
      H -= h;
    }
    idx_put[idx] = true;
  }

  REP(i, N) { cout << ans[i].first << " " << ans[i].second << endl; }
  return 0;
}
