#include <bits/stdc++.h>

#include <atcoder/all>

#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)

using namespace std;
using namespace atcoder;

using mint = modint998244353;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int64_t N;
  cin >> N;
  const int M = 6;
  vector A(N, vector<int64_t>(M));
  REP(i, N) {
    REP(j, M) { cin >> A[i][j]; }
  }

  // Collect unique values from the matrix
  vector<pair<int64_t, int64_t>> Xs;
  REP(i, N) {
    REP(j, M) { Xs.emplace_back(A[i][j], i); }
  }
  sort(ALL(Xs));

  mint ans;
  int prev = 0;
  mint dice_comb = 1;
  // Number of daices that have appeared
  vector<int64_t> cnt(N);
  int unseen_dice = N;

  // Iterate through each dice value
  for (auto [x, i] : Xs) {
    // Probability that the value is equal or greater than x
    // i.e. complementary probability that the numbers are less than x

    mint p = (unseen_dice == 0) ? dice_comb / mint(M).pow(N) : 0;
    ans += (mint(1) - p) * (x - prev);
    prev = x;

    if (cnt[i] == 0) {
      unseen_dice--;
    } else {
      // Update n -> n+1 occurrences
      dice_comb = dice_comb * mint(cnt[i] + 1) / cnt[i];
    }
    cnt[i]++;
  }

  cout << ans.val() << endl;

  return 0;
}
