#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N, A;
  cin >> N >> A;

  vector<int> T(N);
  for (int i = 0; i < N; i++) {
    int t;
    cin >> t;
    T[i] = t;
  }

  int time = 0;
  for (auto t : T) {
    time = (time > t) ? time + A : t + A;
    cout << time << "\n";
  }

  return 0;
}
