#include <bits/stdc++.h>
using namespace std;

struct Segment {
  int l;
  int r;
};

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N, M;
  cin >> N >> M;
  vector<Segment> segments(N);
  for (auto& segment : segments) {
    cin >> segment.l >> segment.r;
  }

  sort(segments.begin(), segments.end());

  int l = 0;
  int r = 0;
  int ans = 0;
  while (l < M) {
  }

  return 0;
}
