#include <bits/stdc++.h>

using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N, M;
  cin >> N >> M;
  vector<int> maxL(M + 1, -1);
  for (int i = 0; i < N; i++) {
    int l, r;
    cin >> l >> r;
    maxL[r] = max(maxL[r], l);
  }

  int64_t ans = 0;
  int l = 1;
  for (int r = 1; r <= M; r++) {
    if (l <= maxL[r]) {
      l = maxL[r] + 1;
    }
    ans += r - l + 1;
  }

  cout << ans << endl;

  return 0;
}
