#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

int dx[4] = {0, 1, 0, -1};
int dy[4] = {1, 0, -1, 0};

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int T;
  cin >> T;
  while (T--) {
    int64_t X1, Y1, R1, X2, Y2, R2;
    cin >> X1 >> Y1 >> R1 >> X2 >> Y2 >> R2;
    auto dist2 = (X1 - X2) * (X1 - X2) + (Y1 - Y2) * (Y1 - Y2);
    auto ans = ((abs(R1 - R2) * abs(R1 - R2) <= dist2) && (dist2 <= (R1 + R2) * (R1 + R2))) ? "Yes" : "No";
    cout << ans << endl;
  }
  return 0;
}
