#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

const unordered_map<string, string> replacements = {{"red", "SSS"}, {"blue", "FFF"}, {"green", "MMM"}};

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N;
  cin >> N;

  int ans = 0;
  REP(n, N) {
    auto i = n + 1;
    ans += (i % 2 == 0) ? i * i * i : -i * i * i;
  }

  cout << ans << "\n";
  return 0;
}
