#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N, M;
  cin >> N >> M;

  vector<int> F(N);

  REP(i, N) { cin >> F[i]; }

  vector<int> A(M, 0);
  REP(i, N) { A[F[i] - 1]++; }

  bool ans_n = true;
  bool ans_m = true;
  REP(i, M) {
    if (A[i] > 1) {
      ans_n = false;
    }
    if (A[i] == 0) {
      ans_m = false;
    }
  }

  if (ans_n) {
    cout << "Yes" << endl;
  } else {
    cout << "No" << endl;
  }

  if (ans_m) {
    cout << "Yes" << endl;
  } else {
    cout << "No" << endl;
  }

  return 0;
}
