#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

void solve() {
  int N, H;
  cin >> N >> H;

  vector<int> t(N);
  vector<int> l(N);
  vector<int> u(N);
  REP(i, N) { cin >> t[i] >> l[i] >> u[i]; }

  auto tmp_t = 0;
  auto tmp_l = H;
  auto tmp_u = H;
  REP(i, N) {
    auto dt = t[i] - tmp_t;
    tmp_l -= dt;  // maximum lower case
    tmp_u += dt;  // minimum upper case
    if (tmp_l > u[i] || tmp_u < l[i]) {
      cout << "No" << endl;
      return;
    }
    tmp_l = max(tmp_l, l[i]);
    tmp_u = min(tmp_u, u[i]);
    tmp_t = t[i];
  }
  cout << "Yes" << endl;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int T;
  cin >> T;
  REP(_, T) { solve(); }

  return 0;
}
