#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N;
  cin >> N;

  vector<int> A(N);
  for (auto& a : A) {
    cin >> a;
  }
  sort(A.rbegin(), A.rend());

  vector<int> B(N - 1);
  for (auto& b : B) {
    cin >> b;
  }
  sort(B.rbegin(), B.rend());

  int ans = -1;
  int j = 0;
  for (int i = 0; i < N; i++) {
    if (j >= (N - 1)) {
      // All boxes are inserted.
      break;
    }
    if (A[i] > B[j]) {
      if (ans == -1) {
        ans = A[i];
        continue;
      } else {
        cout << -1 << endl;
        return 0;
      }
    }
    j++;
  }
  if (ans == -1) {
    ans = A[N - 1];
  }

  cout << ans << endl;

  return 0;
}
