#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

auto squares = []() {
  vector<int64_t> sq;
  const int64_t MAX = 1e4;
  int64_t n = 1;
  while (n <= MAX) {
    sq.push_back(n * n);
    ++n;
  }
  return sq;
}();

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N;
  cin >> N;

  int size = squares.size();
  vector<int64_t> val;
  REP(i, size) {
    REP3(j, i + 1, size) {
      auto sum = squares[i] + squares[j];
      if (sum > N) break;
      val.push_back(sum);
    }
  }

  sort(ALL(val));
  vector<int64_t> ans;
  int prev = -1;
  int cnt = 0;
  for (auto a : val) {
    if (a == prev) {
      cnt++;
    } else {
      if (cnt == 1) {
        ans.push_back(prev);
      }
      cnt = 1;
    }
    prev = a;
  }
  if (cnt == 1) {
    ans.push_back(prev);
  }
  cout << ans.size() << endl;
  for (auto v : ans) {
    cout << v << ' ';
  }

  return 0;
}
