#include <bits/stdc++.h>
using namespace std;

const string YES = "Yes";
const string NO = "No";

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int64_t N, S;
  cin >> N >> S;
  vector<int64_t> A(N);
  int64_t sum = 0;
  for (auto& a : A) {
    cin >> a;
    sum += a;
  }

  int64_t rem = S % sum;
  int tmp = 0;
  int j = 0;
  bool ans = false;
  for (int i = 0; i < N; i++) {
    while (tmp < rem) {
      // Add back
      tmp += A[j];
      j = (j + 1) % N;
    }
    if (tmp == rem) {
      ans = true;
      break;
    }
    // Decreace front
    tmp -= A[i];
  }

  auto out = ans ? YES : NO;
  cout << out << endl;

  return 0;
}
