#include <bits/stdc++.h>
using namespace std;

const string YES = "Yes";
const string NO = "No";

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int64_t N, S;
  cin >> N >> S;
  vector<int64_t> A(N);
  int64_t sum = 0;
  for (auto& a : A) {
    cin >> a;
    sum += a;
  }

  int i = 0;
  // initial is maximum multiple sum smaller than S
  int64_t tmp = (S / sum) * sum;
  while (tmp < S) {
    tmp += A[i];
    i = (i + 1) % N;
  }
  bool ans = false;
  for (int j = 0; j < N; j++) {
    // Decreace front
    tmp -= A[j];
    if (tmp == S) {
      ans = true;
      break;
    }
    while (tmp < S) {
      // Add back
      tmp += A[i];
      i = (i + 1) % N;
      if (tmp == S) {
        ans = true;
        break;
      }
    }
  }

  auto out = ans ? YES : NO;
  cout << out << endl;

  return 0;
}
