#include <bits/stdc++.h>

#include <atcoder/all>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

using mint = modint998244353;

mint nCr(int n, int r) {
  if (r < 0 || r > n) return 0;
  static vector<mint> fact(1, 1), inv_fact(1, 1);
  while ((int)fact.size() <= n) {
    fact.push_back(fact.back() * (int)fact.size());
    inv_fact.push_back(inv_fact.back() / (int)inv_fact.size());
  }
  return fact[n] * inv_fact[r] * inv_fact[n - r];
}

// Combinations with repetitions: nHr = nCr(n + r - 1, r)
mint nHr(int n, int r) {
  if (n == 0 && r == 0) return 1;
  if (n <= 0 || r < 0) return 0;
  return nCr(n + r - 1, r);
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int a, b, c;
  cin >> a >> b >> c;

  mint ans;
  auto cnt = [](int a, int b, int c) -> mint {
    mint ret;
    // loop for groups with a and c
    for (int g = 2;; g++) {
      // split group into ga and gc: aaa|a ccc|c
      int gc = g / 2;
      int ga = g - gc;
      if (ga > a || gc > c) break;
      // b must be enough to fill gaps between groups
      if (b < g - 1) break;
      mint now = nHr(ga, a - ga);
      now *= nHr(gc, c - gc);
      now *= nHr(a + c + 1, b - (g - 1));
      ret += now;
    }
    return ret;
  };
  ans += cnt(a, b, c);
  ans += cnt(c, b, a);

  cout << ans.val() << endl;

  return 0;
}
