#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

const std::string YES = "Yes";
const std::string NO = "No";

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int64_t N, Q;
  cin >> N >> Q;
  vector<bool> v(N);
  int64_t cnt = 0;
  REP(i, Q) {
    int64_t A;
    cin >> A;
    A--;
    v[A] = !v[A];

    auto l_valid = (A - 1 >= 0);
    auto r_valid = (A + 1 < N);
    // x ? x
    auto a1 = l_valid && !v[A - 1] && r_valid && !v[A + 1];
    // - ? x
    auto a2 = !l_valid && r_valid && !v[A + 1];
    // x ? -
    auto a3 = l_valid && !v[A - 1] && !r_valid;
    // o ? o
    auto a4 = l_valid && v[A - 1] && r_valid && v[A + 1];
    // - ? -
    auto a5 = !l_valid && !r_valid;
    if (v[A]) {
      if (a1 || a2 || a3 || a5) {
        cnt++;
      } else if (a4) {
        cnt--;
      }
    } else {
      if (a4) {
        cnt++;
      } else if (a1 || a2 || a3 || a5) {
        cnt--;
      }
    }
    cout << cnt << "\n";
  }

  return 0;
}
