#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

const std::string YES = "Yes";
const std::string NO = "No";

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int64_t N, Q;
  cin >> N >> Q;
  // Add 2 extra elements to handle edge cases
  vector<bool> v(N + 2);
  int64_t cnt = 0;
  REP(i, Q) {
    int64_t A;
    cin >> A;

    // Check the neighbor values
    auto isRaising = [&](int64_t i) { return (v[i] == 0) && (v[i + 1] == 1); };
    int64_t tmp = 0;
    if (isRaising(A - 1)) tmp--;
    if (isRaising(A)) tmp--;
    // Toggle the state of the A-th element
    v[A] = !v[A];
    if (isRaising(A - 1)) tmp++;
    if (isRaising(A)) tmp++;

    cnt += tmp;
    cout << cnt << "\n";
  }

  return 0;
}
