#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N;
  cin >> N;
  vector<pair<int, int>> P(N);
  REP(i, N) { cin >> P[i].second >> P[i].first; }

  sort(ALL(P));
  int ans = 1;  // First one is ok
  auto min_y = P.front().second;
  REP(i, N - 1) {
    auto [x2, y2] = P[i + 1];
    if (y2 < min_y) {
      ans++;
    }
    min_y = min(min_y, y2);
  }
  cout << ans << endl;

  return 0;
}
