#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

struct Learn {
  int skill;
  int A;
  int B;
};

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N;
  cin >> N;

  vector<int64_t> A(N);
  REP(i, N) {
    int Ai;
    cin >> Ai;
    Ai--;
    A[Ai]++;
  }

  int64_t multi_comb = 0;
  for (auto a : A) {
    if (a != 1) {
      // nC2
      multi_comb += a * (a - 1) / 2;
    }
  }

  int64_t ans = 0;
  for (auto a : A) {
    const auto comb = a * (a - 1) / 2;
    ans += a * (multi_comb - comb);
  }

  cout << ans << endl;

  return 0;
}
