#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int H, W;
  cin >> H >> W;

  vector<string> S(H);
  REP(i, H) { cin >> S[i]; }

  auto check = [&](int h1, int h2, int w1, int w2) -> bool {
    for (auto i = h1; i <= h2; i++) {
      for (auto j = w1; j <= w2; j++) {
        auto h = h1 + h2 - i;
        auto w = w1 + w2 - j;
        if (S[i][j] != S[h][w]) {
          return false;
        }
      }
    }
    return true;
  };

  int ans = 0;
  REP(h1, H) {
    REP3(h2, h1, H) {
      REP(w1, W) {
        REP3(w2, w1, W) {
          if (check(h1, h2, w1, w2)) {
            ans++;
          }
        }
      }
    }
  }
  cout << ans << endl;
  return 0;
}
