#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

int64_t solve(std::string S) {
  unordered_set<string> us;
  int size = S.size();
  for (int i = 0; i < size; i++) {
    for (int j = i; j < size; j++) {
      us.emplace(S.substr(i, j - i + 1));
    }
  }
  return us.size();
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  std::string S;
  std::cin >> S;
  auto ans = solve(S);
  std::cout << ans << '\n';
  return 0;
}
