#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  char Sab, Sac, Sbc;
  cin >> Sab >> Sac >> Sbc;
  int A = 0;
  int B = 0;
  int C = 0;
  if (Sab == '<') {
    B++;
  } else {
    A++;
  }
  if (Sac == '<') {
    C++;
  } else {
    A++;
  }
  if (Sbc == '<') {
    C++;
  } else {
    B++;
  }

  if (A == 1) {
    cout << 'A' << endl;
  } else if (B == 1) {
    cout << 'B' << endl;
  } else {
    cout << 'C' << endl;
  }

  return 0;
}
