#include <bits/stdc++.h>

#include <atcoder/all>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N, D;
  cin >> N >> D;

  vector<int> A(N);
  REP(i, N) { cin >> A[i]; }

  set<int> st;
  st.insert(1e9 + D);
  st.insert(-D);

  int64_t ans = 0;
  int l = 0;
  REP(r, N) {
    auto will_insert = A[r];
    while (true) {
      auto it = st.lower_bound(will_insert);
      auto value = *it;
      auto next = (value - will_insert) >= D;
      auto prev_value = *prev(it);
      auto prev = (will_insert - prev_value) >= D;
      if (next && prev) {
        break;
      }
      st.erase(A[l]);
      l++;
    }
    st.insert(will_insert);
    ans += (r - l + 1);
  }

  cout << ans << endl;
  return 0;
}
