#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N, Q;
  cin >> N >> Q;

  int l = 1;
  int r = 2;
  int ans = 0;
  for (int i = 0; i < Q; i++) {
    char h;
    int t;
    cin >> h >> t;
    if (h == 'L') {
      if (l > r) {
        if (t < r) {
          // Clockwise (loop)
          ans += ((N - l) + t);
        } else {
          // No loop
          ans += abs(l - t);
        }
      } else {
        if (t > r) {
          // Counter clockwise (loop)
          ans += ((N - t) + l);
        } else {
          // No loop
          ans += abs(l - t);
        }
      }
      l = t;
    } else {
      if (l > r) {
        if (t > l) {
          // Counter clockwise (loop)
          ans += ((N - t) + r);
        } else {
          // No loop
          ans += abs(r - t);
        }
      } else {
        if (t < l) {
          // Clockwise (loop)
          ans += ((N - r) + t);
        } else {
          // No loop
          ans += abs(r - t);
        }
      }
      r = t;
    }
  }

  cout << ans << endl;

  return 0;
}
