#!/usr/bin/env python3
# from typing import *



# def solve(N: int, X: int, S: List[int], C: List[int], P: List[int]) -> float:
def solve(N, X, S, C, P):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, X = map(int, input().split())
    S = [None for _ in range(N)]
    C = [None for _ in range(N)]
    P = [None for _ in range(N)]
    for i in range(N):
        S[i], C[i], P[i] = map(int, input().split())
    a = solve(N, X, S, C, P)
    print(a)

if __name__ == '__main__':
    main()
