#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


double solve(int N, int64_t X, const std::vector<int64_t> &S, const std::vector<int64_t> &C, const std::vector<int64_t> &P) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N;
    int64_t X;
    std::cin >> N;
    std::vector<int64_t> S(N), C(N), P(N);
    std::cin >> X;
    REP (i, N) {
        std::cin >> S[i] >> C[i] >> P[i];
    }
    auto ans = solve(N, X, S, C, P);
    std::cout << ans << '\n';
    return 0;
}
