#include <bits/stdc++.h>

#include <atcoder/all>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N;
  cin >> N;

  // Edges from cost
  const int M = 1e4;
  vector<vector<pair<int, int>>> edges(M);
  REP(i, N) {
    for (int j = i + 1; j < N; j++) {
      int A;
      cin >> A;
      edges[A].emplace_back(i, j);
    }
  }

  // Build MST with Kruskal's algorithm
  vector<vector<pair<int, int>>> G(N);
  dsu uf(N);
  REP(c, M) {
    for (auto& [u, v] : edges[c]) {
      if (uf.same(u, v)) {
        continue;
      }
      uf.merge(u, v);
      G[u].emplace_back(v, c);
      G[v].emplace_back(u, c);
    }
  }

  // Create distance matrix with BFS
  const int INF = 1001001001;
  vector<vector<int>> dist(N, vector<int>(N, INF));
  REP(sv, N) {
    queue<int> q;
    auto& d = dist[sv];
    d[sv] = 0;
    q.push(sv);
    while (!q.empty()) {
      int v = q.front();
      q.pop();
      for (auto& [to, cost] : G[v]) {
        if (d[to] != INF) {
          continue;
        }
        d[to] = d[v] + cost;
        q.push(to);
      }
    }
  }

  // Check distance
  REP(c, M) {
    for (auto& [u, v] : edges[c]) {
      if (dist[u][v] != c) {
        cout << "No\n";
        return 0;
      }
    }
  }

  cout << "Yes\n";
  return 0;
}
