#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N;
  cin >> N;

  vector<int> A(N);
  for (auto& a : A) {
    cin >> a;
  }

  vector<int> K(N);
  set<int> S;
  for (int i = 0; i < N; i++) {
    S.emplace(A[i]);
    K[i] = S.size();
  }

  vector<int> K_sum(N + 1);
  K_sum[1] = K[0];
  for (int i = 0; i < N; i++) {
    K_sum[i + 1] = K[i] + K_sum[i];
  }

  int ans = 0;
  for (int i = 0; i < N; i++) {
    ans += K[i + 1] - K[i];
  }

  cout << ans << endl;

  return 0;
}
