#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int64_t L, R, D, U;
  cin >> L >> R >> D >> U;

  // count fulfilled squares for the quadrant
  auto f = [](int64_t x_max, int64_t x_min, int64_t y_max, int64_t y_min) -> int64_t {
    x_max = max(x_max, 0L);
    x_min = max(x_min, 1L);
    y_max = max(y_max, 0L);
    y_min = max(y_min, 1L);
    auto m = max(x_max, y_max);
    int64_t cnt = 0;
    for (int i = 1; i <= m; i++) {
      if (i % 2 == 0) {
        if (x_min <= i && i <= x_max) {
          cnt += i - x_min;
        }
        if (y_min <= i && i <= y_max) {
          cnt += i - y_min;
        }
        if (x_min <= i && i <= x_max && y_min <= i && i <= y_max) {
          cnt++;
        }
      }
    }
    return cnt;
  };

  int64_t ans = 0;
  // calc all quadrant
  if (R > 0 && U > 0) {
    ans += f(R, L, U, D);
  }
  if (L < 0 && U > 0) {
    ans += f(-L, -R, U, D);
  }
  if (L < 0 && D < 0) {
    ans += f(-L, -R, -D, -U);
  }
  if (R > 0 && D < 0) {
    ans += f(R, L, -D, -U);
  }
  // x-axis
  if (D <= 0 && U >= 0) {
    ans += (R / 2);
    ans -= (L / 2);
  }
  // y-axis
  if (L <= 0 && R >= 0) {
    ans += (U / 2);
    ans -= (D / 2);
  }
  // zero point
  if (L <= 0 && R >= 0 && D <= 0 && U >= 0) {
    ans++;
  }

  cout << ans << endl;

  return 0;
}
