#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

int64_t MAX = 1e6 + 1;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int64_t L, R, D, U;
  cin >> L >> R >> D >> U;

  int64_t ans = 0;
  // count all columns with |x| > |y|
  for (int64_t x = L; x <= R; x++) {
    if (x % 2 == 0) {
      auto u = min(U, abs(x) - 1L);
      auto d = max(D, -abs(x) + 1L);
      auto sum = u - d + 1;  // tree-plant
      ans += max(sum, 0L);   // for y-axis
    }
  }

  // count all rows with |y| >= |x|
  for (int64_t y = D; y <= U; y++) {
    if (y % 2 == 0) {
      auto r = min(R, abs(y));
      auto l = max(L, -abs(y));
      auto sum = r - l + 1;  // tree-plant
      ans += max(sum, 0L);   // for x-asis
    }
  }

  cout << ans << endl;

  return 0;
}
