#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int Q;
  cin >> Q;

  priority_queue<int, std::vector<int>, std::greater<int>> H;

  REP(i, Q) {
    int q, h;
    cin >> q >> h;

    switch (q) {
      case 1: {
        H.emplace(h);
      } break;
      case 2: {
        while (!H.empty() && H.top() <= h) {
          H.pop();
        }
      } break;
      default:
        break;
    }
    cout << H.size() << "\n";
  }
  return 0;
}
