#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

const unordered_map<string, string> um{
    {"N", "S"}, {"E", "W"}, {"W", "E"}, {"S", "N"}, {"NE", "SW"}, {"NW", "SE"}, {"SE", "NW"}, {"SW", "NE"},
};

std::string solve(std::string D) { return um.at(D); }

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  std::string D;
  std::cin >> D;
  auto ans = solve(D);
  std::cout << ans << '\n';
  return 0;
}
