#include <bits/stdc++.h>

#include <atcoder/all>

#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int64_t X, Y, Z;
  cin >> X >> Y >> Z;

  // X + a = (Y + a) * Z
  // a = (X - Y * Z) / (Z - 1)
  auto a = div(X - Y * Z, Z - 1);
  auto ans = (a.quot >= 0 && a.rem == 0) ? "Yes" : "No";
  cout << ans << endl;
  return 0;
}
