#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

void solve() {
  int64_t N, W;
  cin >> N >> W;

  vector<int> C(N);
  REP(i, N) { cin >> C[i]; }

  if (N <= W) {
    cout << 0 << endl;
    return;
  }

  vector<int64_t> C_sum(2 * W);
  REP(i, N) { C_sum[i % (2 * W)] += C[i]; }

  int64_t tmp = 0;
  REP(i, W) { tmp += C_sum[i]; }
  int64_t ans = tmp;
  REP(i, 2 * W) {
    tmp -= C_sum[i];
    tmp += C_sum[(i + W) % (2 * W)];
    ans = min(ans, tmp);
  }
  cout << ans << endl;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int T;
  cin >> T;

  REP(_, T) { solve(); }

  return 0;
}
