#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N;
  cin >> N;
  vector<int> A(N);
  REP(i, N) cin >> A[i];

  vector<bool> P_N(N + 1);
  vector<int> P(N, -1);
  REP(i, N) {
    if (P_N[A[i]]) {
      cout << "No\n";
      return 0;
    }
    if (A[i] != -1) {
      P_N[A[i]] = true;
      P[i] = A[i];
    }
  }
  int n = 0;
  for (int i = 1; i < N + 1; ++i) {
    if (!P_N[i]) {
      while (P[n] != -1) ++n;
      P[n] = i;
      P_N[i] = true;
    }
  }

  cout << "Yes\n";
  REP(i, N) { cout << P[i] << " "; }
  cout << "\n";

  return 0;
}
