#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 10)  # TODO: edit here
    S = [[None for _ in range(2 * N + 4)] for _ in range(2 * N + 4)]
    M = random.randint(1, 10)  # TODO: edit here
    T = [[None for _ in range(2 * M + 4)] for _ in range(2 * M + 4)]
    for j in range(N + 4):
        for i in range(N):
            S[i + j][i + j] = random.randint(1, 10)  # TODO: edit here
    for j in range(M + 4):
        for i in range(M):
            T[i + j][i + j] = random.randint(1, 10)  # TODO: edit here
    print(N, M)
    for j in range(N + 4):
        print(*[S[i + j][i + j] for i in range(N)])
    for j in range(M + 4):
        print(*[T[i + j][i + j] for i in range(M)])

if __name__ == "__main__":
    main()
