#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N;
  cin >> N;

  vector<string> S(N);

  size_t maxLen = 0;
  for (auto& str : S) {
    cin >> str;
    maxLen = max(maxLen, str.size());
  }

  vector<string> T(maxLen);
  for (size_t i = S.size(); i > 0; i--) {
    auto str = S[i - 1];
    size_t j = 0;
    while (j < str.size()) {
      T[j].push_back(str[j]);
      j++;
    }
    while (j < maxLen) {
      T[j].push_back('*');
      j++;
    }
  }

  for (auto t : T) {
    for (size_t i = t.size(); i > 0; i--) {
      if (t[i - 1] == '*') {
        t.pop_back();
      } else {
        break;
      }
    }

    cout << t << "\n";
  }

  return 0;
}
