#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iomanip>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>

using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  string X;
  cin >> X;

  while (true) {
    auto c = X.back();
    if (c == '0') {
      X.pop_back();
    } else if (c == '.') {
      X.pop_back();
      break;
    } else {
      break;
    }
  }

  cout << X << endl;

  return 0;
}
