#include <bits/stdc++.h>

#include <atcoder/all>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

using mint = modint998244353;

void solve() {
  uint64_t N, M;
  cin >> N >> M;

  // x range: l <= N < r
  uint64_t l = 1;
  mint ans = 0;
  REP(e, 19) {
    uint64_t r = min(l * 10 - 1, N);
    if (l > r) break;  // overflow
    uint64_t g = gcd(l * 10 - 1, M);
    ans += mint(N / (M / g)) * (r - l + 1UL);
    l *= 10;
  }
  cout << ans.val() << endl;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int T;
  cin >> T;
  REP(_, T) { solve(); }

  return 0;
}
