#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int H, W, N;
  cin >> H >> W >> N;
  unordered_map<int, int> value_row;
  REP(i, H) {
    REP(j, W) {
      int a;
      cin >> a;
      value_row[a] = i;
    }
  }

  vector<int> B(N);
  REP(i, N) { cin >> B[i]; }

  vector<int> cnt(H);
  REP(k, N) {
    if (value_row.contains(B[k])) {
      cnt[value_row[B[k]]]++;
    }
  }
  int ans = *max_element(ALL(cnt));

  cout << ans << endl;

  return 0;
}
