#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int H, W, N;
  cin >> H >> W >> N;
  vector A(H, vector<int>(W));
  REP(i, H) {
    REP(j, W) { cin >> A[i][j]; }
  }

  vector<int> B(N);
  REP(i, N) { cin >> B[i]; }

  int ans = 0;
  REP(i, H) {
    int tmp = 0;
    REP(j, W) {
      REP(k, N) {
        if (A[i][j] == B[k]) {
          tmp++;
        }
      }
    }
    ans = max(ans, tmp);
  }

  cout << ans << endl;

  return 0;
}
