#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N, M;
  cin >> N >> M;
  vector<string> S(N);
  REP(i, N) { cin >> S[i]; }

  unordered_set<string> patterns;
  auto calc_pattern = [&](int row_start, int col_start) {
    string pattern;
    REP(i, M) {
      REP(j, M) { pattern += S[row_start + i][col_start + j]; }
    }
    return pattern;
  };

  REP(i, N - M + 1) {
    REP(j, N - M + 1) {
      auto p = calc_pattern(i, j);
      patterns.insert(p);
    }
  }

  cout << patterns.size() << endl;

  return 0;
}
