#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

void chmin(int64_t &a, int64_t b) {
  if (a > b) {
    a = b;
  }
}
void chmax(int64_t &a, int64_t b) {
  if (a < b) {
    a = b;
  }
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int64_t H, W;
  cin >> H >> W;
  vector<vector<int64_t>> A(H, vector<int64_t>(W));
  REP(i, H) {
    REP(j, W) { cin >> A[i][j]; }
  }
  auto N = H + W - 1;
  vector<int64_t> P(N);
  REP(i, N) { cin >> P[i]; }

  const int64_t INF = 1e18;
  vector dp(H, vector<int64_t>(W, INF));
  dp[H - 1][W - 1] = 0;
  for (int i = H - 1; i >= 0; --i) {
    for (int j = W - 1; j >= 0; --j) {
      dp[i][j] += P[i + j];
      dp[i][j] -= A[i][j];
      chmax(dp[i][j], 0LL);
      if (i > 0) {
        chmin(dp[i - 1][j], dp[i][j]);
      }
      if (j > 0) {
        chmin(dp[i][j - 1], dp[i][j]);
      }
    }
  }
  cout << dp[0][0] << '\n';

  return 0;
}
