#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

const std::string YES = "Yes";
const std::string NO = "No";
bool solve(int N, int M, std::vector<int64_t> &A, std::vector<int64_t> &B) {
  sort(A.begin(), A.end());
  sort(B.begin(), B.end());

  std::vector<int64_t> C;
  C.insert(C.end(), A.begin(), A.end());
  C.insert(C.end(), B.begin(), B.end());
  sort(C.begin(), C.end());

  size_t index = C.size();
  for (int i = 0; i < N; i++) {
    auto itr = find(C.begin(), C.end(), A[i]);
    size_t index_next = distance(C.begin(), itr);
    if (index + 1 == index_next) {
      return true;
    }
    index = index_next;
  }
  return false;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  int N, M;
  std::cin >> N;
  std::vector<int64_t> A(N);
  std::cin >> M;
  std::vector<int64_t> B(M);
  REP(i, N) { std::cin >> A[i]; }
  REP(i, M) { std::cin >> B[i]; }
  auto ans = solve(N, M, A, B);
  std::cout << (ans ? YES : NO) << '\n';
  return 0;
}
