#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

struct Learn {
  int skill;
  int A;
  int B;
};

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N;
  cin >> N;

  vector<int> skills(N + 1);
  stack<Learn> st;
  REP(i, N) {
    int A, B;
    cin >> A >> B;
    if (A == 0 && B == 0) {
      skills[i + 1] = 1;
    } else {
      st.emplace(i + 1, A, B);
    }
  }

  auto dfs = [&](auto&& dfs, int skill, int learn) -> void {
    // Prevent dead loop
    if (skills[skill] == -1) {
      return;
    }
    skills[skill] = -1;

    if (skills[learn] == 0) {
      dfs(dfs, skill, learn);
    }
    if (skills[learn] == 1) {
      skills[skill] = 1;
    } else {
      skills[skill] = 0;
    }
  };

  while (!st.empty()) {
    auto [skill, a, b] = st.top();
    st.pop();
    dfs(dfs, skill, a);
    dfs(dfs, skill, b);
    if (skills[a] == 1 || skills[b] == 1) {
      skills[skill] = 1;
    } else {
      skills[skill] = -1;
    }
  }

  int ans = 0;
  for (auto s : skills) {
    if (s == 1) {
      ans++;
    }
  }
  cout << ans << '\n';

  return 0;
}
