#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

struct Learn {
  int skill;
  int A;
  int B;
};

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N;
  cin >> N;

  vector<int> skills(N + 1);
  vector<vector<int>> req(N + 1, vector<int>());
  unordered_set<int> us;
  REP(i, N) {
    int A, B;
    cin >> A >> B;
    if (A == 0 && B == 0) {
      skills[i + 1] = 1;
      us.insert(i + 1);
    } else {
      req[A].push_back(i + 1);
      req[B].push_back(i + 1);
    }
  }

  while (!us.empty()) {
    auto it = us.begin();
    auto skill = *it;
    for (auto r : req[skill]) {
      if (skills[r] == 0) {
        us.insert(r);
      }
      skills[r] = 1;
    }
    us.erase(it);
  }

  int ans = 0;
  for (auto s : skills) {
    if (s == 1) {
      ans++;
    }
  }
  cout << ans << '\n';

  return 0;
}
