#include <bits/stdc++.h>

#include <atcoder/all>

#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

const int MAX = 5000;
modint C[MAX + 1][MAX + 1];

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int T, M;
  cin >> T >> M;
  modint::set_mod(M);
  C[0][0] = 1;
  REP(i, MAX) {
    REP(j, i + 1) {
      C[i + 1][j] += C[i][j];
      C[i + 1][j + 1] += C[i][j];
    }
  }

  REP(t, T) {
    int N;
    cin >> N;
    int s = 0;
    modint ans = 1;
    REP(i, N) {
      int c;
      cin >> c;
      s += c;
      ans *= C[s][c];
    }

    cout << ans.val() << "\n";
  }

  return 0;
}
