#include <bits/stdc++.h>

#include <atcoder/all>

#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

// calclate prime numbers
vector<int> sieve(int n) {
  vector<bool> is_prime(n + 1, true);
  is_prime[0] = is_prime[1] = false;
  for (int i = 2; i * i <= n; i++) {
    if (is_prime[i]) {
      for (int j = i * i; j <= n; j += i) {
        is_prime[j] = false;
      }
    }
  }
  vector<int> primes;
  for (int i = 2; i <= n; i++) {
    if (is_prime[i]) primes.push_back(i);
  }
  return primes;
}

int factorial_exp(int n, int p) {
  int exp = 0;
  while (n > 0) {
    n /= p;
    exp += n;
  }
  return exp;
}

static vector<int> PRIMES = sieve(5000);

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int T, M;
  cin >> T >> M;

  REP(t, T) {
    int N;
    cin >> N;
    vector<int64_t> C(N);
    REP(i, N) { cin >> C[i]; }

    int64_t len = 0;
    REP(i, N) { len += C[i]; }

    unordered_map<int, int> exp;
    for (int p : PRIMES) {
      exp[p] = factorial_exp(len, p);
    }

    for (int c : C) {
      for (int p : PRIMES) {
        exp[p] -= factorial_exp(c, p);
      }
    }

    int64_t ans = 1;
    for (int p : PRIMES) {
      int e = exp[p];
      for (int i = 0; i < e; i++) {
        ans *= p;
      }
    }

    cout << ans % M << "\n";
  }

  return 0;
}
