#include <bits/stdc++.h>

#include <atcoder/all>

#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

const int di[4] = {-1, 0, 1, 0};
const int dj[4] = {0, 1, 0, -1};

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int H, W;
  cin >> H >> W;
  vector<string> S(H);
  REP(i, H) { cin >> S[i]; }

  using Cell = pair<int, int>;
  vector<Cell> updatedCells;
  REP(i, H) {
    REP(j, W) {
      if (S[i][j] == '#') {
        updatedCells.emplace_back(i, j);
      }
    }
  }

  int ans = 0;
  while (!updatedCells.empty()) {
    ans += updatedCells.size();
    vector<Cell> nextCells;
    for (auto [i, j] : updatedCells) {
      REP(v, 4) {
        int ni = i + di[v];
        int nj = j + dj[v];
        if (0 <= ni && ni < H && 0 <= nj && nj < W && S[ni][nj] == '.') {
          int cnt = 0;
          REP(v2, 4) {
            int mi = ni + di[v2];
            int mj = nj + dj[v2];
            if (0 <= mi && mi < H && 0 <= mj && mj < W && S[mi][mj] == '#') {
              cnt++;
            }
          }
          if (cnt == 1) {
            nextCells.emplace_back(ni, nj);
          }
        }
      }
    }
    for (auto [i, j] : nextCells) {
      S[i][j] = '#';
    }
    swap(updatedCells, nextCells);
  }

  cout << ans << "\n";

  return 0;
}
