#include <bits/stdc++.h>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  vector<string> S(8);
  for (auto& s : S) {
    cin >> s;
  }

  vector<bool> row(8, false);
  vector<bool> column(8, false);
  for (int i = 0; i < 8; i++) {
    for (int j = 0; j < 8; j++) {
      if (S[i][j] == '#') {
        row[i] = true;
        column[j] = true;
      }
    }
  }

  int r_ok = 0;
  for (auto r : row) {
    if (!r) {
      r_ok++;
    }
  }

  int c_ok = 0;
  for (auto c : column) {
    if (!c) {
      c_ok++;
    }
  }

  cout << r_ok * c_ok << endl;

  return 0;
}
