#include <bits/stdc++.h>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int64_t X;
  cin >> X;

  int64_t N = 0;
  int64_t tmp = 1;
  while (tmp != X) {
    N++;
    tmp *= N;
  }

  cout << N << endl;

  return 0;
}
