#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

void solve(void) {
  int64_t N;
  cin >> N;
  string S;
  cin >> S;

  bitset<18> bs_state;
  stack<bitset<18>> bs_stack;
  vector<bool> bs_queued(1 << N);
  bs_stack.emplace("0");
  while (!bs_stack.empty()) {
    auto bs_state = bs_stack.top();
    bs_stack.pop();
    REP(i, N) {
      // Alread included
      if (bs_state[i]) {
        continue;
      }
      auto tmp = bs_state;
      tmp.set(i);
      auto state = tmp.to_ulong();
      if (bs_queued[state]) {
        continue;
      }
      auto isDengerous = S[state - 1] == '1';
      if (!isDengerous) {
        if (state == (1 << N) - 1) {
          cout << "Yes" << '\n';
          return;
        }
        bs_queued[state] = true;
        bs_stack.push(tmp);
      }
    }
  }
  cout << "No" << '\n';
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int64_t N;
  cin >> N;

  REP(i, N) { solve(); }

  return 0;
}
