#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

int64_t solve(int N, const std::vector<int64_t> &A) {
  int64_t ans = A[0];
  priority_queue<int64_t> pq;
  for (int i = 1; i < 2 * N - 1; i += 2) {
    pq.push(A[i]);
    pq.push(A[i + 1]);
    ans += pq.top();
    pq.pop();
  }
  return ans;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  int T;
  std::cin >> T;
  REP(i, T) {
    int N;
    std::cin >> N;
    std::vector<int64_t> A(2 * N);
    REP(j, 2 * N) { std::cin >> A[j]; }
    auto ans = solve(N, A);
    std::cout << ans << '\n';
  }
  return 0;
}
