#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

const string YES = "Yes";

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int L, R;
  cin >> L >> R;

  bool isLeft = (L == 1);
  bool isRight = (R == 1);
  auto ans = (isLeft && !isRight) ? "Yes" : (!isLeft && isRight) ? "No" : "Invalid";

  cout << ans << endl;

  return 0;
}
