#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N;
  cin >> N;

  vector<int> A(N);
  for (auto &a : A) {
    cin >> a;
  }

  // j - Aj = i + Ai
  vector<int64_t> I(N);
  REP(i, N) {
    auto idx = i + A[i];
    if (idx < N) {
      I[idx]++;
    }
  }

  vector<int64_t> J(N);
  REP(j, N) {
    auto idx = j - A[j];
    if (idx >= 0) {
      J[idx]++;
    }
  }

  int64_t ans = 0;
  REP(i, N) { ans += I[i] * J[i]; }

  std::cout << ans << '\n';
  return 0;
}
