#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N;
  cin >> N;

  vector<int> A(N);
  for (auto &a : A) {
    cin >> a;
  }
  vector<int> dA(N);

  REP(i, N) { dA[i] = A[i] - i; }

  unordered_map<int64_t, int64_t> diff_cnt;
  for (int i = 1; i < N; ++i) {
    auto diff = (A[0] + A[i]) - i;
    diff_cnt[diff]++;
  }

  int64_t ans = 0;
  REP(i, N) {
    auto offset = A[0] - A[i] - i;
    ans += diff_cnt[offset];
    if (i != 0) {
      auto diff = (A[0] + A[i]) - i;
      diff_cnt[diff]--;
    }
  }

  std::cout << ans << '\n';
  return 0;
}
