#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int X, N;
  cin >> X >> N;
  vector<int> W(N);
  vector<bool> W_b(N, false);
  REP(i, N) { cin >> W[i]; }

  int Q;
  cin >> Q;

  REP(_, Q) {
    int P;
    cin >> P;
    P--;
    if (!W_b[P]) {
      W_b[P] = true;
      X += W[P];
    } else {
      W_b[P] = false;
      X -= W[P];
    }
    cout << X << endl;
  }

  return 0;
}
