#include <bits/stdc++.h>

#include <atcoder/all>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

using mint = modint998244353;

template <typename T>
struct Sieve {
  T n;
  vector<T> primes;
  vector<T> factor;

  Sieve(T n) : n(n), factor(n + 1, -1) {
    for (int64_t i = 2; i <= n; i++) {
      if (factor[i] != -1) {
        continue;
      }
      factor[i] = i;
      primes.push_back(i);
      for (int64_t j = i * i; j <= n; j += i) {
        if (factor[j] == -1) {
          factor[j] = i;
        }
      }
    }
  }

  bool is_prime(T i) const { return factor[i] == i; }
  vector<pair<T, T>> prime_factorization(T x) const {
    vector<pair<T, T>> res;
    while (x != 1) {
      if (res.empty() || res.back().first != factor[x]) {
        res.emplace_back(factor[x], 0);
      }
      res.back().second++;
      x /= factor[x];
    }
    return res;
  }
};
Sieve<int> sieve(1e7);

void solve() {
  int N;
  cin >> N;

  vector<int> A(N);
  REP(i, N) { cin >> A[i]; }

  vector<vector<pair<int, int>>> factors(N);
  map<int, vector<int>> factor_map;
  REP(i, N) {
    factors[i] = sieve.prime_factorization(A[i]);
    for (auto [f, c] : factors[i]) {
      factor_map[f].push_back(c);
    }
  }
  for (auto& [f, v] : factor_map) {
    sort(v.rbegin(), v.rend());
  }

  // base lcm
  mint base = 1;
  for (auto& [f, v] : factor_map) {
    // add dummy
    v.push_back(0);
    base *= mint(f).pow(v[0]);
  }

  REP(i, N) {
    mint ans = base;
    for (auto [p, e] : factors[i]) {
      auto& v = factor_map[p];
      auto d = (e == v[0]) ? v[0] - v[1] : 0;
      ans /= mint(p).pow(d);
    }
    cout << ans.val() << " ";
  }
  cout << endl;
};

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int T;
  cin >> T;

  while (T--) {
    solve();
  }
  return 0;
}
