#include <bits/stdc++.h>

#include <atcoder/all>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

struct Loop {
  vector<int> nodes;
  int64_t sum;
};

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N, Q;
  cin >> N >> Q;
  vector<int> A(N);
  REP(i, N) { cin >> A[i]; }

  vector<Loop> loops;

  REP(_, Q) {
    int T, B;
    cin >> T >> B;
    int64_t ans = 0;

    cout << ans << '\n';
  }

  return 0;
}
