#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

using Pi = pair<int64_t, int64_t>;
using Vp = vector<Pi>;

int64_t pow2(int64_t e) { return (int64_t)1 << e; }

Vp solve(int64_t L, int64_t R) {
  Vp ans;
  while (L != R) {
    int64_t i = 0;
    auto a = pow2(i);
    auto tmp_a = pow2(i + 1);
    while ((L % tmp_a == 0) && L + tmp_a <= R) {
      a = tmp_a;
      i++;
      tmp_a = pow2(i);
    }
    ans.emplace_back(Pi(L, L + a));
    L += a;
  }
  return ans;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  int64_t L, R;
  std::cin >> L >> R;
  Vp ans = solve(L, R);
  std::cout << ans.size() << '\n';
  for (auto p : ans) {
    std::cout << p.first << ' ' << p.second << '\n';
  }
  return 0;
}
