#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N, M, K;
  cin >> N >> M >> K;

  vector<int> H(N);
  REP(i, N) { cin >> H[i]; }
  sort(ALL(H));

  vector<int> B(M);
  REP(i, M) { cin >> B[i]; }
  sort(ALL(B));

  int j = 0;
  int ans = 0;
  REP(i, N) {
    while (j < M && B[j] < H[i]) {
      j++;
    }
    if (j >= M) {
      break;
    }
    ans++;
    j++;
  }

  if (ans >= K) {
    cout << "Yes" << endl;
  } else {
    cout << "No" << endl;
  }
  return 0;
}
