#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

struct Reindeer {
  int64_t W;
  int64_t P;
  bool is_rided = true;
};

void solve() {
  int N;
  cin >> N;
  vector<Reindeer> A(N);
  int64_t total_W = 0;
  int64_t total_P = 0;
  REP(i, N) {
    cin >> A[i].W >> A[i].P;
    total_W += A[i].W;
  }

  vector<int> idx_P(N);
  iota(ALL(idx_P), 0);
  sort(ALL(idx_P), [&](const int& a, const int& b) { return A[a].P > A[b].P; });

  vector<int> idx_W(N);
  iota(ALL(idx_W), 0);
  sort(ALL(idx_W), [&](const int& a, const int& b) { return A[a].W > A[b].W; });

  int64_t p = 0;
  int64_t w = 0;
  int ride = N;
  REP(i, N) {
    if (total_P >= total_W) {
      break;
    }

    while (!A[idx_P[p]].is_rided) p++;
    while (!A[idx_W[w]].is_rided) w++;

    if (A[idx_P[p]].P > A[idx_W[w]].W) {
      A[idx_P[p]].is_rided = false;
      total_P += A[idx_P[p]].P;
      total_W -= A[idx_P[p]].W;
      ride--;
    } else {
      A[idx_W[w]].is_rided = false;
      total_P += A[idx_W[w]].P;
      total_W -= A[idx_W[w]].W;
      ride--;
    }
  }
  cout << ride << '\n';
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int T;
  cin >> T;

  REP(_, T) { solve(); }

  return 0;
}
