#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

struct Reindeer {
  int64_t W;
  int64_t P;
  int64_t eff;
};

void solve() {
  int N;
  cin >> N;
  vector<Reindeer> A(N);
  int64_t total_W = 0;
  int64_t total_P = 0;
  REP(i, N) {
    cin >> A[i].W >> A[i].P;
    A[i].eff = A[i].P + A[i].W;
    total_W += A[i].W;
  }

  sort(ALL(A), [](const Reindeer& a, const Reindeer& b) { return a.eff > b.eff; });

  int ride = N;
  REP(i, N) {
    if (total_P >= total_W) {
      break;
    }

    total_P += A[i].P;
    total_W -= A[i].W;
    ride--;
  }
  cout << ride << '\n';
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int T;
  cin >> T;

  REP(_, T) { solve(); }

  return 0;
}
