#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

auto solve(void) {
  int N;
  cin >> N;
  vector<int> A(N);
  for (auto& a : A) {
    cin >> a;
  }
  sort(ALL(A), [](int a, int b) { return std::abs(a) < std::abs(b); });
  for (int i = 1; i < N - 1; i++) {
    auto est = static_cast<int64_t>(A[i]) * A[1] / A[0];
    if (est != A[i + 1]) {
      cout << "No" << endl;
      return;
    }
  }
  cout << "Yes" << endl;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  int T;
  std::cin >> T;
  REP(t, T) { solve(); }
  return 0;
}
