#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  string S, T;
  cin >> S;
  cin >> T;

  int size = S.size();
  vector<int> diff(size);
  for (int i = 0; i < size; i++) {
    diff[i] = (S[i] > T[i]) ? -1 : (S[i] < T[i]) ? 1 : 0;
  }

  vector<string> X;
  for (int i = 0; i < size; i++) {
    if (diff[i] == -1) {
      S[i] = T[i];
      X.emplace_back(S);
    }
  }
  for (int i = 0; i < size; i++) {
    auto ir = size - i - 1;
    if (diff[ir] == 1) {
      S[ir] = T[ir];
      X.emplace_back(S);
    }
  }

  cout << X.size() << "\n";
  for (auto x : X) {
    cout << x << "\n";
  }

  return 0;
}
