#include <bits/stdc++.h>
using namespace std;

int numMulD = 9;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N;
  cin >> N;

  int ans = 0;
  for (int i = 1; i <= numMulD; i++) {
    for (int j = 1; j <= numMulD; j++) {
      auto mul = i * j;
      if (mul != N) {
        ans += mul;
      }
    }
  }

  cout << ans << endl;

  return 0;
}
