#include <bits/stdc++.h>

#include <atcoder/all>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

using mint = modint998244353;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N, M;
  cin >> N >> M;
  // max edge: 2e5
  // max node: 2e5
  vector<vector<int>> G(N);
  vector<int> A(N);
  REP(i, M) {
    int U, V;
    cin >> U >> V;
    U--;
    V--;
    // edge num of each nodes
    G[U].push_back(i + 1);
    G[V].push_back(i + 1);
    // max edge num of each nodes
    A[U] = i + 1;
    A[V] = i + 1;
  }

  // single edge case
  if (M == 1) {
    cout << 2 << endl;
    return 0;
  }

  // multiple edge case
  auto minA = *min_element(ALL(A));
  vector<int> minN;
  REP(i, N) {
    if (A[i] == minA) {
      minN.push_back(i);
    }
  }

  // check if multiple edge exist
  mint ans = 0;
  for (auto n : minN) {
    auto size = (minN.size() == 1) ? G[n].size() : G[n].size() - 1;
    for (int i = 0; i < size; i++) {
      ans += mint(2).pow(G[n][i]);
    }
  }
  cout << ans.val() << endl;
  return 0;
}
