#include <bits/stdc++.h>

#include <atcoder/all>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

using mint = modint998244353;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N, M;
  cin >> N >> M;
  vector<pair<int, int>> nodes(M);
  REP(i, M) {
    int U, V;
    cin >> U >> V;
    U--;
    V--;
    nodes[i] = {U, V};
  }

  // For fast calculation of 2^i
  vector<mint> cost(M);
  cost[0] = 2;
  REP(i, M - 1) { cost[i + 1] = cost[i] * 2; }

  mint ans = 0;
  dsu uf(N);
  int cc = N;
  for (int i = M - 1; i >= 0; i--) {
    auto [U, V] = nodes[i];
    if (cc == 2 && !uf.same(U, V)) {
      // the node shouuld be disconnected.
      ans += cost[i];
    } else {
      // connect the node.
      if (!uf.same(U, V)) {
        uf.merge(U, V);
        cc--;
      }
    }
  }

  cout << ans.val() << endl;
  return 0;
}
