#include <bits/stdc++.h>
using namespace std;

const string YES = "Yes";
const string NO = "No";

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int A, B, C;
  cin >> A >> B >> C;

  auto ABCisSame = (A == B) && (A == C);
  auto ABisSame = (A + B) == C;
  auto BCisSame = (B + C) == A;
  auto ACisSame = (A + C) == B;
  auto ans = (ABCisSame || ABisSame || BCisSame || ACisSame) ? YES : NO;
  cout << ans << endl;

  return 0;
}
