#include <bits/stdc++.h>

#include <atcoder/all>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  string S;
  cin >> S;

  vector<vector<int>> char_idx(3);
  REP(i, S.size()) { char_idx[S[i] - 'A'].push_back(i); }

  int ans = 0;
  int bi = 0;
  int ci = 0;
  REP(i, char_idx[0].size()) {
    auto a_idx = char_idx[0][i];
    while (bi < char_idx[1].size() && char_idx[1][bi] < a_idx) {
      bi++;
    }
    if (bi >= char_idx[1].size()) {
      break;
    }
    auto b_idx = char_idx[1][bi];
    while (ci < char_idx[2].size() && char_idx[2][ci] < b_idx) {
      ci++;
    }
    if (ci >= char_idx[2].size()) {
      break;
    }
    ans++;
    bi++;
    ci++;
  }

  cout << ans << endl;
  return 0;
}
