#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N, M;
  cin >> N >> M;

  string S;
  cin >> S;

  string T;
  cin >> T;

  int ans = INT32_MAX;
  REP(i, N - M + 1) {
    int tmp = 0;
    REP(j, M) {
      auto s = S[i + j];
      auto t = T[j];
      tmp += s >= t ? s - t : (s + 10) - t;
    }
    ans = min(ans, tmp);
  }

  cout << ans << endl;

  return 0;
}
