#include <bits/stdc++.h>

#include <atcoder/all>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N;
  cin >> N;

  vector<string> S(N);
  int x, y;
  REP(i, N) {
    cin >> x >> y;
    S[i] = to_string(x) + to_string(y);
  }
  vector<int> idx(N);
  iota(ALL(idx), 0);
  sort(ALL(idx), [&](const int& a, const int& b) { return S[a] < S[b]; });

  REP(i, N) { cout << idx[i] + 1 << " "; }
  cout << endl;

  return 0;
}
