#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int64_t N, M;
  std::cin >> N >> M;
  vector<int> A(N + 1);
  REP(i, M) {
    int L, R;
    cin >> L >> R;
    L--;
    A[L]++;
    A[R]--;
  }

  REP(i, N) { A[i + 1] += A[i]; }
  auto ans = *min_element(A.begin(), A.begin() + N);

  cout << ans << endl;

  return 0;
}
