#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int64_t N, M;
  std::cin >> N >> M;
  vector<pair<int, int>> A(M);
  REP(i, M) {
    int L, R;
    cin >> L >> R;
    L--;
    R--;
    A[i] = {L, R};
  }

  sort(ALL(A));

  int ans = INT_MAX;
  priority_queue<int, std::vector<int>, std::greater<int>> pq;
  int tmp = 0;
  REP(i, N) {
    while (tmp < M && i >= A[tmp].first) {
      auto end = A[tmp].second;
      pq.emplace(end);
      tmp++;
    }

    while (!pq.empty() && i > pq.top()) {
      pq.pop();
    }
    ans = min(ans, static_cast<int>(pq.size()));
  }

  cout << ans << endl;

  return 0;
}
