#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int64_t N, M;
  cin >> N >> M;

  vector<pair<int64_t, int64_t>> X;
  REP(i, M) {
    int64_t A, B;
    cin >> A >> B;
    X.emplace_back(A - B, A);
  }
  sort(ALL(X));

  int64_t ans = 0;
  for (auto [cost, a] : X) {
    if (N < a) {
      continue;
    }
    // Bin N shall remain at least a
    auto free = N - a;
    // Other bin can be used to pay for the cost
    auto x = free / cost + 1;
    ans += x;
    N -= x * cost;
  }

  cout << ans << "\n";

  return 0;
}
