#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int64_t N, M;
  cin >> N >> M;

  map<int64_t, int64_t> X;
  REP(i, M) {
    int64_t A, B;
    cin >> A >> B;
    if (X.contains(A)) {
      auto diff = A - B;
      if (diff > (A - X[A])) {
        X[A] = B;
      }
    } else {
      X[A] = B;
    }
  }

  int64_t ans = 0;
  for (auto x : X) {
    N += x;
    if (N < 0) {
      break;
    }
    ans++;
  }

  cout << ans << "\n";

  return 0;
}
