#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  string S;
  cin >> S;

  unordered_map<char, int64_t> um_l;
  unordered_map<char, int64_t> um_r;
  for (auto s : S) {
    um_r[s]++;
  }

  int64_t ans = 0;
  // loop based on j
  for (auto s : S) {
    // Remove j char from right side
    um_r[s]--;

    for (auto [key, value] : um_l) {
      if (um_r.contains(key)) {
        ans += value * um_r[key];
      }
    }
    // Remove j char to left side
    um_l[s]++;
  }
  cout << ans << endl;
  return 0;
}
