#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

int64_t solve(std::string S) {
  int64_t ans = 0;
  char tmp = 'n';
  for (auto c : S) {
    ans++;
    if (tmp == 'n') {
      tmp = c;
      ans += tmp - '0';
      continue;
    }

    if ((tmp != 'n') && (c > tmp)) {
      ans += 10;
    }
    tmp = c;
  }
  return ans;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  std::string S;
  std::cin >> S;
  auto ans = solve(S);
  std::cout << ans << '\n';
  return 0;
}
