#include <bits/stdc++.h>

#include <atcoder/all>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int64_t N;
  cin >> N;

  vector<int64_t> A(N);
  unordered_map<int64_t, int64_t> um_r;
  REP(i, N) {
    cin >> A[i];
    um_r[A[i]]++;
  }

  unordered_map<int64_t, int64_t> um_l;
  int64_t ans = 0;
  for (auto a : A) {
    um_r[a]--;
    um_l[a]++;

    auto d = div(a, 5L);
    if (d.rem == 0) {
      ans += um_l[d.quot * 7] * um_l[d.quot * 3];
      ans += um_r[d.quot * 7] * um_r[d.quot * 3];
    }
  }

  cout << ans << endl;

  return 0;
}
