#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int H, W, Q;
  cin >> H >> W >> Q;

  REP(i, Q) {
    int q;
    cin >> q;
    if (q == 1) {
      int R;
      cin >> R;
      cout << W * R << endl;
      H -= R;
    } else {
      int C;
      cin >> C;
      cout << H * C << endl;
      W -= C;
    }
  }
  return 0;
}
