#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int64_t N;
  cin >> N;

  vector<int64_t> A(N);
  REP(i, N) { cin >> A[i]; }
  sort(ALL(A));

  vector<int64_t> ans;
  // case1: max(A)
  int cnt = 0;
  bool is_same = true;
  REP(i, N) {
    if (A[i] == A[N - 1]) {
      cnt++;
    }
  }
  auto remain = N - cnt;
  if (remain % 2 == 0) {
    // spilit case
    REP(i, remain / 2) {
      if ((A[i] + A[remain - 1 - i]) != A[N - 1]) {
        is_same = false;
        break;
      }
    }
  } else {
    is_same = false;
  }
  if (is_same) {
    ans.push_back(A[N - 1]);
  }

  // case2: sum of min max
  auto sum = A[0] + A[N - 1];
  bool valid = true;
  if (A.size() % 2 == 0) {
    REP(i, N / 2) {
      if (A[i] + A[N - 1 - i] != sum) {
        valid = false;
        break;
      }
    }
  } else {
    valid = false;
  }
  if (valid) {
    ans.push_back(sum);
  }

  for (auto a : ans) {
    cout << a << " ";
  }
  cout << endl;
  return 0;
}
