#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

const std::string YES = "Yes";
const std::string NO = "No";
bool solve(int n, const std::vector<int64_t> &A) {
  vector<int> cnt(13);
  for (auto a : A) {
    cnt[a - 1]++;
  }
  sort(cnt.rbegin(), cnt.rend());
  return (cnt[0] >= 3) && (cnt[1] >= 2);
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  int n = 7;
  std::vector<int64_t> a(n);
  REP(i, n) { std::cin >> a[i]; }
  auto ans = solve(n, a);
  std::cout << (ans ? YES : NO) << '\n';
  return 0;
}
