#include <bits/stdc++.h>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int Q;
  cin >> Q;

  queue<int64_t> q;
  int64_t now = 0;

  for (int i = 0; i < Q; i++) {
    int query;
    cin >> query;

    switch (query) {
      case 1: {
        q.push(now);
      } break;
      case 2: {
        int T;
        cin >> T;
        now += T;
      } break;
      case 3: {
        int H;
        cin >> H;
        int ans = 0;
        while (!q.empty()) {
          auto t = q.front();
          auto eplaced = now - t;
          if (eplaced >= H) {
            q.pop();
            ans++;
          } else {
            break;
          }
        }
        cout << ans << "\n";
      } break;
      default:
        break;
    }
  }

  return 0;
}
