#include <bits/stdc++.h>

#include <atcoder/all>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N, Q;
  cin >> N >> Q;

  vector<int> A(N);
  REP(i, N) { cin >> A[i]; }
  sort(ALL(A));
  A.emplace_back(INT32_MAX);

  REP(_, Q) {
    int X, Y;
    cin >> X >> Y;

    auto it_l = lower_bound(ALL(A), X);
    auto idx_l = distance(A.begin(), it_l);

    if (X + Y <= *it_l) {
      cout << X + Y - 1 << endl;
      continue;
    }

    int wa = idx_l;
    int ac = A.size();
    while (wa + 1 < ac) {
      int wj = (wa + ac) / 2;
      int len = A[wj] - X;
      int cnt = wj - idx_l;
      if (len - cnt >= Y) {
        ac = wj;
      } else {
        wa = wj;
      }
    }

    int cnt = wa - idx_l + 1;
    cout << X + Y - 1 + cnt << endl;
  }

  return 0;
}
