#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N, A, B;
  cin >> N >> A >> B;

  string S;
  cin >> S;

  vector<int> sum_a(N + 1), sum_b(N + 1);
  REP(i, N) {
    sum_a[i + 1] = sum_a[i] + (S[i] == 'a' ? 1 : 0);
    sum_b[i + 1] = sum_b[i] + (S[i] == 'b' ? 1 : 0);
  }

  int64_t ans = 0;
  REP(l, N) {
    int ra, rb;
    {
      int wa = l, ac = N + 1;
      while (wa + 1 < ac) {
        int wj = (wa + ac) / 2;
        if (sum_a[wj] - sum_a[l] >= A) {
          ac = wj;
        } else {
          wa = wj;
        }
      }
      ra = ac;
    }

    {
      int ac = l, wa = N + 1;
      while (ac + 1 < wa) {
        int wj = (wa + ac) / 2;
        if (sum_b[wj] - sum_b[l] < B) {
          ac = wj;
        } else {
          wa = wj;
        }
      }
      rb = wa;
    }
    ans += max(0, rb - ra);
  }

  cout << ans << endl;
  return 0;
}
