#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N, A, B;
  cin >> N >> A >> B;

  string S;
  cin >> S;

  int r_a = -1, r_b = -1;
  int cnt_a = 0, cnt_b = 0;
  int64_t ans = 0;

  REP(l, N) {
    while (cnt_a < A) {
      r_a++;
      if (r_a >= N) {
        cout << ans << endl;
        return 0;
      }

      if (S[r_a] == 'a') {
        cnt_a++;
      }
    }

    while (r_b < N && cnt_b < B) {
      r_b++;
      if (S[r_b] == 'b') {
        cnt_b++;
      }
    }

    ans += max(0, r_b - r_a);

    if (S[l] == 'a') {
      cnt_a--;
    } else {
      cnt_b--;
    }
  }

  cout << ans << endl;
  return 0;
}
