#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N, A, B;
  cin >> N >> A >> B;

  string S;
  cin >> S;

  int r = -1;
  int cnt_a = 0, cnt_b = 0;
  int ans = 0;

  REP(l, N) {
    while (cnt_a < A) {
      r++;
      if (r >= N) {
        cout << ans << endl;
        return 0;
      }

      if (S[r] == 'a') {
        cnt_a++;
      } else {
        cnt_b++;
      }
    }

    auto tmp_a = cnt_a;
    auto tmp_b = cnt_b;
    auto tmp_r = r;

    while (tmp_b < B) {
      ans++;
      if (tmp_r + 1 >= N) {
        break;
      }
      if (S[tmp_r + 1] == 'a') {
        tmp_r++;
        tmp_a++;
      } else {
        tmp_r++;
        tmp_b++;
      }
    }

    if (S[l] == 'a') {
      cnt_a--;
    } else {
      cnt_b--;
    }
  }

  cout << ans << endl;
  return 0;
}
