#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

const std::string YES = "Yes";
const std::string NO = "No";
bool solve(std::string S) {
  unordered_map<char, int> um;
  for (auto s : S) {
    um[s]++;
  }

  unordered_map<int, int> kind;
  for (auto p : um) {
    kind[p.second]++;
  }

  for (auto p : kind) {
    if ((p.second != 0) && (p.second != 2)) {
      return false;
    }
  }

  return true;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  std::string S;
  std::cin >> S;
  auto ans = solve(S);
  std::cout << (ans ? YES : NO) << '\n';
  return 0;
}
