#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

vector<pair<int, int>> generate_rle(const vector<int>& A) {
  vector<pair<int, int>> rle;
  int N = A.size();
  if (N == 0) {
    return rle;
  }
  int prev = A[0];
  int count = 1;
  for (int i = 1; i < N; ++i) {
    if (A[i] == prev) {
      ++count;
    } else {
      rle.emplace_back(prev, count);
      prev = A[i];
      count = 1;
    }
  }
  rle.emplace_back(prev, count);
  return rle;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N;
  cin >> N;
  vector<int> A(N);
  REP(i, N) { cin >> A[i]; }

  auto rle = generate_rle(A);
  bool is_continue = true;
  while (is_continue) {
    is_continue = false;
    vector<pair<int, int>> tmp_rle;
    for (const auto& [value, count] : rle) {
      auto cnt = count % 4;
      if (cnt != 0) {
        if (!tmp_rle.empty() && tmp_rle.back().first == value) {
          tmp_rle.back().second += cnt;
          is_continue = true;
        } else {
          tmp_rle.emplace_back(value, cnt);
        }
      }
    }
    rle = tmp_rle;
  }

  int ans = 0;
  for (const auto& [_, count] : rle) {
    ans += count;
  }

  cout << ans << endl;

  return 0;
}
