#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

bool isPalidrome(int64_t i, int64_t base) {
  string s;
  while (i > 0) {
    auto [quot, rem] = std::div(i, base);
    i = quot;
    s.push_back('0' + rem);
  }
  string rs = s;
  reverse(ALL(rs));
  return s == rs;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int64_t A, N;
  cin >> A >> N;

  int64_t ans = 0;
  int64_t i = 1;
  while (i <= N) {
    // palindromic check with A base
    if (isPalidrome(i, A)) {
      ans += i;
    }

    // Next palindromic number
    auto str_int = to_string(i);
    // include center digit
    auto half_size = (str_int.size() + 1) / 2;
    auto isCenterDigit = (str_int.size() % 2 == 1);
    auto str_half_int = stoll(str_int.substr(0, half_size));
    str_half_int++;
    auto str_half = to_string(str_half_int);
    auto carry_over = str_half.size() != half_size;
    if (carry_over && isCenterDigit) {
      str_half.pop_back();
    }
    str_int = str_half;
    if (carry_over ^ isCenterDigit) {
      str_half.pop_back();
    }
    reverse(ALL(str_half));

    str_int += str_half;
    i = stoll(str_int);
  }

  cout << ans << "\n";

  return 0;
}
