#include <bits/stdc++.h>

#include <atcoder/all>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int64_t N;
  cin >> N;
  vector<int64_t> A(N);
  REP(i, N) { cin >> A[i]; }
  vector<int64_t> B(N);
  REP(i, N) { cin >> B[i]; }
  vector<int64_t> C(N);
  REP(i, N) { cin >> C[i]; }

  A[N - 1] = 0;
  A[N - 2] = 0;
  B[0] = 0;
  B[N - 1] = 0;
  C[0] = 0;
  C[1] = 0;

  vector<vector<int64_t>> dp(3, vector<int64_t>(N + 1, 0));
  REP(i, N) {
    dp[0][i + 1] = dp[0][i] + A[i];
    dp[1][i + 1] = max(dp[0][i] + A[i], dp[1][i] + B[i]);
    dp[2][i + 1] = max(dp[1][i] + B[i], dp[2][i] + C[i]);
  }

  cout << dp[2][N] << endl;
  return 0;
}
