#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N;
  cin >> N;
  vector<vector<int>> B(N);
  int K;
  REP(i, N) {
    cin >> K;
    REP(j, K) {
      int b;
      cin >> b;
      b--;
      B[b].push_back(i);
    }
  }
  REP(i, N) {
    cout << B[i].size() << " ";
    REP(j, B[i].size()) { cout << B[i][j] + 1 << " "; }
    cout << endl;
  }
  return 0;
}
