#include <bits/stdc++.h>
using namespace std;

unordered_map<char, pair<int, int>> moveS = {{'U', {-1, 0}}, {'D', {1, 0}}, {'L', {0, -1}}, {'R', {0, 1}}};

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int H, W, X, Y;
  cin >> H >> W >> X >> Y;
  X--;
  Y--;

  vector<vector<char>> S(H, vector<char>(W));
  for (auto& str : S) {
    for (auto& c : str) {
      cin >> c;
    }
  }

  string T;
  cin >> T;

  int ans = 0;
  for (auto& t : T) {
    auto m = moveS[t];
    auto x = X + m.first;
    auto y = Y + m.second;
    switch (S[x][y]) {
      case '.': {
        X = x;
        Y = y;
      } break;

      case '@': {
        // visited
        S[x][y] = '.';
        ans++;
        X = x;
        Y = y;
      } break;
      default:
        break;
    }
  }

  cout << X + 1 << " " << Y + 1 << " " << ans << endl;

  return 0;
}
