#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

std::string solve(int64_t N, int64_t K, std::string S) {
  auto ans = S;
  int num_o = 0;
  REP(i, N) {
    if (S[i] == 'o') {
      num_o++;
      if (i + 1 < N) {
        ans[i + 1] = '.';
      }
      if (i > 0) {
        ans[i - 1] = '.';
      }
    }
  }

  unordered_map<int, vector<int>> um_consecutive_num;
  REP(i, N) {
    if (ans[i] == '?') {
      auto l = i;
      while (i < N && ans[i] == '?') {
        i++;
      }
      auto consecutive_num = i - l;
      um_consecutive_num[consecutive_num].emplace_back(l);
    }
  }

  int max_o = 0;
  for (auto [key, v] : um_consecutive_num) {
    max_o += (key + 1) / 2 * v.size();
  }

  auto remain_o = K - num_o;
  if (remain_o == max_o) {
    for (auto [key, v] : um_consecutive_num) {
      if (key % 2 == 0) {
        continue;
      }
      for (auto index : v) {
        bool o = true;
        for (int i = 0; i < key; i++) {
          ans[i + index] = o ? 'o' : '.';
          o = !o;
        }
      }
    }
  } else if (remain_o == 0) {
    for (auto& s : ans) {
      if (s == '?') {
        s = '.';
      }
    }
  }
  return ans;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  int64_t N, K;
  std::string S;
  std::cin >> N >> K >> S;
  auto ans = solve(N, K, S);
  std::cout << ans << '\n';
  return 0;
}
