#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  string S;
  cin >> S;

  vector<pair<char, int>> rle;
  REP(i, (int)S.size()) {
    if (rle.empty() || rle.back().first != S[i]) {
      rle.emplace_back(S[i], 1);
    } else {
      rle.back().second++;
    }
  }

  int ans = 0;
  REP(i, (int)rle.size() -1 ) {
    if(rle[i].first +1 == rle[i + 1].first) {
      ans += min(rle[i].second, rle[i + 1].second);
    }
  }

  cout << ans << endl;
  return 0;
}
