#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N, K;
  cin >> N >> K;
  vector<int> A(N);
  for (auto& a : A) {
    cin >> a;
  }

  vector<int> B;
  for (int i = (N - K); i < N; i++) {
    B.emplace_back(A[i]);
  }
  for (int i = 0; i < (N - K); i++) {
    B.emplace_back(A[i]);
  }

  for (auto b : B) {
    cout << b << " ";
  }
  cout << endl;
  return 0;
}
