#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N, K;
  cin >> N >> K;
  vector<int> A(N);
  for (auto& a : A) {
    cin >> a;
  }

  rotate(A.begin(), A.begin() + N - K, A.end());
  for (auto a : A) {
    cout << a << " ";
  }
  cout << endl;
  return 0;
}
