#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

int64_t solve(int N, int64_t K, const std::vector<int64_t> &P) {
  // {value, element}
  unordered_map<int64_t, int64_t> um;
  for (int i = 0; i < N; i++) {
    um[P[i]] = i + 1;
  }

  set<int64_t> s;
  for (int i = 1; i <= K; i++) {
    s.insert(um[i]);
  }

  int64_t ans = *s.rbegin() - *s.begin();

  for (int i = 1; i < N - K + 1; i++) {
    s.erase(um[i]);
    s.insert(um[i + K]);
    const int64_t tmp = *s.rbegin() - *s.begin();
    ans = min(ans, tmp);
  }
  return ans;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  int N;
  int64_t K;
  std::cin >> N;
  std::vector<int64_t> P(N);
  std::cin >> K;
  REP(i, N) { std::cin >> P[i]; }
  auto ans = solve(N, K, P);
  std::cout << ans << '\n';
  return 0;
}
