#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N, M;
  cin >> N >> M;
  vector<vector<int>> G(N);
  REP(i, M) {
    int A, B;
    cin >> A >> B;
    A--;
    B--;
    G[A].push_back(B);
  }

  vector<bool> visited(N, false);
  queue<int> q;
  q.push(0);
  while (!q.empty()) {
    int v = q.front();
    q.pop();
    if (visited[v]) {
      continue;
    }
    visited[v] = true;
    for (int nv : G[v]) {
      if (!visited[nv]) {
        q.push(nv);
      }
    }
  }

  int ans = 0;
  REP(i, N) {
    if (visited[i]) {
      ans++;
    }
  }

  cout << ans << endl;

  return 0;
}
