#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N, M;
  cin >> N >> M;

  vector<int64_t> A(N);
  for (int i = 0; i < N; i++) {
    int64_t a;
    cin >> a;
    A[i] = a;
  }

  vector<int64_t> B(M);
  for (int i = 0; i < M; i++) {
    int64_t b;
    cin >> b;
    B[i] = b;
  }

  sort(A.begin(), A.end());
  sort(B.begin(), B.end());

  int64_t ans = 0;
  int i = 0;
  for (auto b : B) {
    bool found = false;
    for (int j = i; j < N; j++) {
      if (A[j] >= b) {
        ans += A[j];
        found = true;
        i = j + 1;
        break;
      }
    }
    if (!found) {
      ans = -1;
      break;
    }
  }

  cout << ans << "\n";

  return 0;
}
