#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

const string YES = "Yes";
const string NO = "No";

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int64_t N;
  cin >> N;
  vector<int64_t> A(N);
  auto ans = false;
  REP(i, N) {
    int64_t Ai;
    cin >> Ai;
    A[i] = Ai;
  }

  int64_t X;
  cin >> X;

  REP(i, N) {
    if (A[i] == X) {
      ans = true;
      break;
    }
  }

  std::cout << (ans ? YES : NO) << '\n';
  return 0;
}
