#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

const string YES = "Yes";
const string NO = "No";

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N, T, A;
  cin >> N >> T >> A;

  int remain = N - T - A;
  bool isTakahashi = T > (A + remain);
  bool isAoki = A > (T + remain);
  string ans = (isTakahashi || isAoki) ? YES : NO;
  cout << ans << endl;

  return 0;
}
