#include <bits/stdc++.h>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int A, B;
  cin >> A >> B;
  auto N = (A + B);
  auto ans = N * N;
  cout << ans << endl;
  return 0;
}
