#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

void solve() {
  int N;
  cin >> N;
  string S;
  cin >> S;

  REP(i, N - 1) {
    if (S[i] <= S[i + 1]) {
      continue;
    }

    const auto s = S[i];
    bool shifted = false;
    for (int j = i; j < N; j++) {
      if (s < S[j]) {
        S.insert(j, {s});
        S.erase(i, 1);
        shifted = true;
        break;
      }
    }
    if (!shifted) {
      S.insert(N, {s});
      S.erase(i, 1);
    }
    break;
  }
  cout << S << endl;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int64_t T;
  std::cin >> T;
  REP(i, T) { solve(); }

  return 0;
}
