#include <bits/stdc++.h>

#include <atcoder/all>

#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

struct G {
  int64_t A;
  int64_t B;
  int64_t C;
};

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N, K;
  cin >> N >> K;
  vector<G> Gs(N);
  REP(i, N) {
    int A, B, C;
    cin >> A >> B >> C;
    Gs[i] = {A, B, C};
  }

  int64_t t = 0;
  int64_t k = 0;
  // accessing order the estimated exit time
  // (exit time, Group index)
  priority_queue<pair<int64_t, int64_t>, vector<pair<int64_t, int64_t>>, greater<pair<int64_t, int64_t>>> q;
  REP(i, N) {
    auto g = Gs[i];
    while (!q.empty() && (g.C + k) > K) {
      auto [est, idx] = q.top();
      q.pop();
      k -= Gs[idx].C;
      t = est;
    }

    int64_t entry = max(t, g.A);
    cout << entry << "\n";
    int64_t exit = entry + g.B;
    q.emplace(exit, i);
    k += g.C;
  }

  cout << '\n';

  return 0;
}
