#include <bits/stdc++.h>

#include <atcoder/all>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N;
  cin >> N;

  vector<pair<int, int>> ab(N);
  REP(i, N) {
    int A, B;
    cin >> A >> B;
    ab[i] = {A, B};
  }
  // Sort by A asc, B desc (Ascending order with slope)
  sort(ALL(ab), [](auto& a, auto& b) { return a.first != b.first ? a.first < b.first : a.second > b.second; });
  vector<int> b(N);
  REP(i, N) { b[i] = ab[i].second; }

  // dp - i: Serched persons, value: Kite position with last selected person
  const int INF = 1e9 + 7;
  vector<int> dp(N + 1, INF);
  dp[0] = -1;
  int ans = 0;
  for (auto bi : b) {
    int i = lower_bound(ALL(dp), bi) - dp.begin();
    dp[i] = bi;
    ans = max(ans, i);
  }

  cout << ans << endl;

  return 0;
}
