#include <bits/stdc++.h>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N;
  cin >> N;
  unordered_map<int, int> um;

  for (int i = 0; i < N; i++) {
    int A;
    cin >> A;
    if (um.find(A) != um.end()) {
      cout << um[A] << " ";
    } else {
      cout << -1 << " ";
    }
    um[A] = i + 1;
  }
  return 0;
}
