#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N, C;
  cin >> N >> C;
  vector<int> T(N);
  for (auto& t : T) {
    cin >> t;
  }

  int ans = 0;
  int prev = -C;
  for (const auto& t : T) {
    if ((t - prev) < C) {
      continue;
    }
    ans++;
    prev = t;
  }

  cout << ans << endl;

  return 0;
}
