#!/usr/bin/env python3
# from typing import *



# def solve(a: str, b: List[str], c: List[str], d: str, e: List[str], f: List[str]) -> int:
def solve(a, b, c, d, e, f):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = input()
    b = [None for _ in range(a)]
    c = [None for _ in range(a)]
    for i in range(a):
        b[i], c[i] = input().split()
    d = input()
    e = [None for _ in range(d)]
    f = [None for _ in range(d)]
    for i in range(d):
        e[i], f[i] = input().split()
    a1 = solve(a, b, c, d, e, f)
    print(a1)

if __name__ == '__main__':
    main()
