#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

std::string solve(int N, std::vector<std::string> &S, std::vector<int64_t> &C) {
  int64_t sum = 0;
  for (auto c : C) {
    sum += c;
  }

  sort(S.begin(), S.end(), [](string s1, string s2) { return s1 < s2; });

  int64_t size = S.size();
  return S[sum % size];
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  int N;
  std::cin >> N;
  std::vector<std::string> S(N);
  std::vector<int64_t> C(N);
  REP(i, N) { std::cin >> S[i] >> C[i]; }
  auto ans = solve(N, S, C);
  std::cout << ans << '\n';
  return 0;
}
