#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N;
  cin >> N;

  vector<int> R(N);
  vector<int> C(N);
  REP(i, N) {
    int r, c;
    cin >> r >> c;
    R[i] = r;
    C[i] = c;
  }
  sort(ALL(R));
  sort(ALL(C));

  auto R_center = (R.front() + R.back()) / 2;
  auto C_center = (C.front() + C.back()) / 2;

  auto dist_R = max(abs(R_center - R.front()), abs(R_center - R.back()));
  auto dist_C = max(abs(C_center - C.front()), abs(C_center - C.back()));

  cout << max(dist_R, dist_C) << '\n';
  return 0;
}
