#include <bits/stdc++.h>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  string S;
  cin >> S;

  vector<int> A;
  int size = S.size();
  int tmp = 0;
  for (int i = 1; i < size; i++) {
    if (S[i] == '-') {
      tmp++;
    } else {
      A.emplace_back(tmp);
      tmp = 0;
    }
  }

  for (auto a : A) {
    cout << a << " ";
  }
  cout << endl;

  return 0;
}
