#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int R, G, B;
  cin >> R >> G >> B;

  string C;
  cin >> C;

  int ans;
  if (C == "Red") {
    ans = min(G, B);
  } else if (C == "Green") {
    ans = min(R, B);
  } else {
    ans = min(R, G);
  }

  cout << ans << endl;

  return 0;
}
