#include <bits/stdc++.h>

#include <atcoder/all>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)

// move priority
char moveN[] = {'R', 'U', 'L', 'D'};
int moveR[] = {0, -1, 0, 1};
int moveC[] = {1, 0, -1, 0};

void solve() {
  int N, A, B;
  cin >> N >> A >> B;
  A--;
  B--;

  // check
  auto isOddMatrix = N % 2 != 0;
  auto isEvenSum = (A + B) % 2 == 0;
  if (isOddMatrix || isEvenSum) {
    cout << "No\n";
    return;
  }
  cout << "Yes\n";

  // Simulate to move
  int h = N;
  int w = N;
  string s;
  // move to the nearest row of the target
  // start from (0, 0)
  while (A >= 2) {
    // move 2 rows
    s += string(N - 1, 'R') + 'D';
    s += string(N - 1, 'L') + 'D';
    h -= 2;
    A -= 2;
  }
  while (B >= 2) {
    // move 2 columns
    s += "DRUR";
    w -= 2;
    B -= 2;
  }
  // near target
  if (A == 0) {
    s += "DR";
    w -= 2;
  } else {
    s += "RD";
    w -= 2;
  }
  // remain columns
  while (w > 1) {
    s += "RURD";
    w -= 2;
  }
  h -= 2;

  // to goal (N - 1, N - 1)
  while (h > 1) {
    // move 2 rows
    s += 'D' + string(N - 1, 'L');
    s += 'D' + string(N - 1, 'R');
    h -= 2;
  }

  cout << s << "\n";
}

int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int T;
  cin >> T;
  REP(_, T) { solve(); }

  return 0;
}
