#include <bits/stdc++.h>

#include <atcoder/all>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)

// move priority
char moveN[] = {'R', 'U', 'L', 'D'};
int moveR[] = {0, -1, 0, 1};
int moveC[] = {1, 0, -1, 0};

void solve() {
  int N, A, B;
  cin >> N >> A >> B;

  // check
  if (N % 2 != 0) {
    // odd matrix cannot filfill the condition
    cout << "No\n";
    return;
  }
  if (A % 2 == B % 2) {
    cout << "No\n";
    return;
  }
  cout << "Yes\n";

  // Simulate to move
  vector<vector<bool>> visited(N, vector<bool>(N, false));
  pair<int, int> pos = {0, 0};
  visited[pos.first][pos.second] = true;
  visited[A - 1][B - 1] = true;
  vector<char> ans(N * N - 1);
  REP(i, ans.size()) {
    for (int j = 0; j < 4; j++) {
      int nx = pos.first + moveR[j];
      int ny = pos.second + moveC[j];
      if (nx < 0 || nx >= N || ny < 0 || ny >= N) {
        continue;
      }
      if (visited[nx][ny]) {
        continue;
      }
      pos = {nx, ny};
      visited[pos.first][pos.second] = true;
      ans[i] = moveN[j];
      break;
    }
  }
  for (char c : ans) {
    cout << c;
  }
  cout << "\n";
}

int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int T;
  cin >> T;
  REP(_, T) { solve(); }

  return 0;
}
