#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

using Pair = std::pair<int, int>;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N, M;
  cin >> N >> M;

  vector<vector<int>> G(N);
  for (int i = 0; i < M; i++) {
    int a, b;
    cin >> a >> b;
    a--;
    b--;
    G[a].emplace_back(b);
  }

  // Dijkstra
  vector<int> G_dist(N, INT32_MAX);
  std::priority_queue<Pair, std::vector<Pair>, std::greater<Pair>> q;
  for (auto next : G[0]) {
    q.emplace(next, 1);
    G_dist[next] = 1;
  }
  while (!q.empty()) {
    auto s = q.top();
    auto from = s.first;
    auto dist = s.second;
    q.pop();

    if (G_dist[from] < dist) {
      // Skip because the queue is not minimum dist
      continue;
    }

    for (const auto& next : G[from]) {
      // Insert if the dist is minimum
      const auto d = G_dist[from] + 1;
      if (d < G_dist[next]) {
        G_dist[next] = d;
        q.emplace(next, d);
      }
    }
  }
  if (G_dist[0] == INT_MAX) {
    cout << -1 << endl;
    return 0;
  }

  cout << G_dist[0] << endl;

  return 0;
}
