#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

int64_t solve(int64_t N, int Q, const std::vector<int64_t> &T) {
  std::vector<bool> v(N, true);
  for (int i = 0; i < Q; i++) {
    auto n = T[i] - 1;
    v[n] = !v[n];
  }

  int64_t ans = 0;
  for (auto it : v) {
    if (it) {
      ans++;
    }
  }
  return ans;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  int64_t N;
  int Q;
  std::cin >> N >> Q;
  std::vector<int64_t> T(Q);
  REP(i, Q) { std::cin >> T[i]; }
  auto ans = solve(N, Q, T);
  std::cout << ans << '\n';
  return 0;
}
