#include <bits/stdc++.h>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N;
  cin >> N;

  vector<int> A(N);
  for (auto& a : A) {
    cin >> a;
  }

  sort(A.begin(), A.end());
  int idx_top = N / 2 - 1;
  int idx_under = N - 1;
  int idx_top_used = -1;
  int64_t ans = 0;
  while ((idx_top >= 0) && (idx_under > idx_top_used)) {
    while (A[idx_top] > A[idx_under] / 2) {
      idx_top--;
    }
    if (idx_top >= 0) {
      ans++;
      if (idx_top_used == -1) {
        idx_top_used = idx_top;
      }
      idx_top--;
    }
    idx_under--;
  }
  cout << ans << endl;

  return 0;
}
