#include <bits/stdc++.h>

#include <atcoder/all>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

int MAX_D = 9;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  vector<string> S2N;
  for (int i = 1; i < 1e9; i *= 2) {
    S2N.push_back(to_string(i));
  }

  vector<int> good;
  auto f = [&](auto f, string S) -> void {
    for (auto& s2N : S2N) {
      auto nS = S + s2N;
      if (nS.size() > MAX_D) {
        break;
      }
      good.push_back(stoi(nS));
      f(f, nS);
    }
  };
  f(f, "");
  sort(ALL(good));
  good.erase(unique(ALL(good)), good.end());

  int N;
  cin >> N;
  cout << good[N - 1] << endl;

  return 0;
}
