#include <bits/stdc++.h>

#include <atcoder/all>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N;
  cin >> N;
  vector<int> A(N);
  REP(i, N) { cin >> A[i]; }

  vector<vector<int>> G(N);
  REP(i, N - 1) {
    int U, V;
    cin >> U >> V;
    U--;
    V--;
    G[U].push_back(V);
    G[V].push_back(U);
  }

  vector<bool> result(N, false);
  vector<bool> visited(N, false);
  unordered_map<int, int> values;
  auto dfs = [&](auto&& self, int v, bool isDuplicate) -> void {
    visited[v] = true;
    values[A[v]]++;
    if (values[A[v]] >= 2) {
      isDuplicate = true;
    }
    if (isDuplicate) {
      result[v] = true;
    }
    for (int u : G[v]) {
      if (!visited[u]) {
        self(self, u, isDuplicate);
      }
    }
    visited[v] = false;
    values[A[v]]--;
  };
  dfs(dfs, 0, false);

  REP(k, N) {
    auto ans = result[k] ? "Yes" : "No";
    cout << ans << "\n";
  }
  return 0;
}
