#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N, M;
  cin >> N >> M;
  vector<int> A(N);
  for (auto& a : A) {
    cin >> a;
  }
  vector<int> B(M);
  for (auto& b : B) {
    cin >> b;
  }

  REP(i, M) {
    REP(j, N) {
      auto it = find(A.begin(), A.end(), B[i]);
      if (it != A.end()) {
        A.erase(it);  // Mark as used
        break;
      }
    }
  }

  int size = A.size();
  REP(i, size) { std::cout << A[i] << " "; }
  std::cout << '\n';
  return 0;
}
