#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int64_t N;
  cin >> N;

  string S;
  cin >> S;

  auto top = 'A';
  int64_t pos_exp = 0;
  int64_t ans_A = 0;
  REP(i, N * 2) {
    if (S[i] == top) {
      ans_A += abs(i - pos_exp);
      pos_exp += 2;
    }
  }

  top = 'B';
  pos_exp = 0;
  int64_t ans_B = 0;
  REP(i, N * 2) {
    if (S[i] == top) {
      ans_B += abs(i - pos_exp);
      pos_exp += 2;
    }
  }

  cout << min(ans_A, ans_B) << '\n';
  return 0;
}
