#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  string S;
  cin >> S;

  vector<int> cnt('z' - 'a' + 1);
  for (char c : S) {
    cnt[c - 'a']++;
  }
  auto max_cnt = *max_element(ALL(cnt));

  vector<bool> is_enable('z' - 'a' + 1);
  REP(i, cnt.size()) { is_enable[i] = (cnt[i] != max_cnt); }

  for (char c : S) {
    if (is_enable[c - 'a']) {
      cout << c;
    }
  }

  return 0;
}
