#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  string S;
  cin >> S;

  vector<pair<char, int>> P('z' - 'a' + 1);
  REP(i, P.size()) {
    P[i].first = 'a' + i;
    P[i].second = 0;
  }

  for (char c : S) {
    P[c - 'a'].second++;
  }
  sort(ALL(P), [](const auto& a, const auto& b) { return a.second > b.second; });

  auto max_cnt = P.front().second;
  vector<bool> is_enable('z' - 'a' + 1);
  REP(i, P.size()) { is_enable[P[i].first - 'a'] = (P[i].second != max_cnt); }

  for (char c : S) {
    if (is_enable[c - 'a']) {
      cout << c;
    }
  }

  return 0;
}
