#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N;
  cin >> N;
  vector<int> A(N);
  int A_sum = 0;
  int A_max = 0;
  for (auto& a : A) {
    cin >> a;
    A_sum += a;
    A_max = max(A_max, a);
  }

  // 通常パターン
  // 全体が2ずつ減少し、終了時に正の整数が1以下になる
  int tmp = A_sum / 2;

  // A_maxが偏っているパターン
  // 終了時に正の整数が2以上になる
  int tmp_a = A_sum - A_max;

  cout << min(tmp, tmp_a) << endl;
  return 0;
}
