#include <bits/stdc++.h>

#include <atcoder/all>

#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int64_t A, B, C;
  cin >> A >> B >> C;

  vector<int64_t> V = {A, B, C};
  sort(ALL(V));
  auto ans = V[2] * 100 + V[1] * 10 + V[0];

  cout << ans << endl;
  return 0;
}
