#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N;
  cin >> N;

  vector<int> A(N);
  REP(i, N) { cin >> A[i]; }

  vector<int> A_idx(N);
  iota(ALL(A_idx), 0);
  sort(ALL(A_idx), [&](int l, int r) { return A[l] < A[r]; });

  REP(i, 3) { cout << A_idx[i] + 1 << " "; }

  cout << endl;
  return 0;
}
