#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  string S;
  cin >> S;
  string ans;
  int size = S.size();
  bool initial = true;
  REP(i, size) {
    if (S[i] == '.' && initial) {
      ans.push_back('o');
      initial = false;
    } else if (!initial && S[i] != '#' && S[i - 1] == '#') {
      ans.push_back('o');
    } else {
      ans.push_back(S[i]);
    }
  }

  std::cout << ans << '\n';
  return 0;
}
