#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N, M;
  cin >> N >> M;

  vector<bitset<10>> S(N);
  for (int i = 0; i < N; i++) {
    string s;
    cin >> s;
    for (int j = 0; j < M; j++) {
      S[i][j] = (s[j] == 'o');
    }
  }

  bitset<10> all;
  for (int j = 0; j < M; j++) {
    all.set(j);
  }

  int ans = N;
  int max = 1 << N;
  for (int i = 0; i < max; i++) {
    bitset<10> bs;
    int cnt = 0;
    for (int b = 0; b < N; b++) {
      if (i & (1 << b)) {
        cnt++;
        bs |= S[b];
      }
    }

    if (bs == all) {
      ans = min(ans, cnt);
    }
  }

  cout << ans << "\n";

  return 0;
}
