#include <bits/stdc++.h>

#include <atcoder/all>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N, L, R;
  cin >> N >> L >> R;

  vector<vector<int>> char_idxs(26);
  REP(i, N) {
    char c;
    cin >> c;
    char_idxs[c - 'a'].push_back(i);
  }

  int64_t ans = 0;
  for (auto& idxs : char_idxs) {
    int size = idxs.size();
    int j_min = 0;
    int j_max = 0;
    for (int i = 0; i < size; i++) {
      while (j_min < size && (idxs[j_min] - idxs[i] < L)) {
        j_min++;
      }
      while (j_max < size && (idxs[j_max] - idxs[i] <= R)) {
        j_max++;
      }
      ans += j_max - j_min + 1;
    }
  }

  cout << ans << endl;
  return 0;
}
