#include <bits/stdc++.h>

#include <atcoder/all>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N, L, R;
  cin >> N >> L >> R;

  string S;
  cin >> S;

  vector<int> char_cnts(26);
  int j_min = 0;
  int j_max = 0;
  int64_t ans = 0;
  REP(i, N) {
    while (j_max < N && j_max - i < R) {
      j_max++;
      char_cnts[S[j_max] - 'a']++;
    }
    while (j_min < N && j_min - i < L - 1) {
      j_min++;
      char_cnts[S[j_min] - 'a']--;
    }
    ans += char_cnts[S[i] - 'a'];
  }

  cout << ans << endl;
  return 0;
}
