#include <bits/stdc++.h>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N;
  cin >> N;

  vector<int> q(N);
  vector<int> r(N);
  for (int i = 0; i < N; i++) {
    cin >> q[i] >> r[i];
  }

  int Q;
  cin >> Q;
  for (int i = 0; i < Q; i++) {
    int t, d;
    cin >> t >> d;
    t--;
    auto ans = (d / q[t]) * q[t] + r[t];
    if (d > ans) {
      ans += q[t];
    }
    cout << ans << "\n";
  }

  return 0;
}
