#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

int64_t pow_i(int64_t x, int64_t y) {
  int64_t ans = 1;
  REP(i, y) { ans *= x; }
  return ans;
}

constexpr int64_t MOD = 998244353;
std::string solve(int64_t N, int64_t M) {
  int64_t ans = 0;
  for (int64_t i = 0; i <= M; i++) {
    ans += pow_i(N, i);
    if (ans > 1000000000) {
      return "inf";
    }
  }
  return to_string(ans);
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  int64_t N, M;
  std::cin >> N >> M;
  auto ans = solve(N, M);
  std::cout << ans << '\n';
  return 0;
}
