#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

struct Learn {
  int skill;
  int A;
  int B;
};

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N, Q;
  cin >> N >> Q;

  int A_idx = 0;
  vector<int> A(N);
  REP(i, N) { cin >> A[i]; }

  vector<int64_t> A_sum(N + 1);
  REP(i, N) { A_sum[i + 1] = A_sum[i] + A[i]; }

  REP(i, Q) {
    int q;
    cin >> q;
    if (q == 1) {
      int c;
      cin >> c;
      A_idx = (A_idx + c + N) % N;
    } else {
      int l, r;
      cin >> l >> r;
      auto L = (A_idx + l - 1) % N;
      auto R = (A_idx + r - 1) % N;
      if (L <= R) {
        cout << A_sum[R + 1] - A_sum[L] << "\n";
      } else {
        cout << A_sum[N] + A_sum[R + 1] - A_sum[L] << "\n";
      }
    }
  }

  return 0;
}
