#include <bits/stdc++.h>

#include <atcoder/all>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N;
  cin >> N;

  vector<int> A(N);
  REP(i, N) { cin >> A[i]; }

  string ans;
  sort(ALL(A));

  auto max_d = A[N - 1];
  int64_t carry = 0;
  int i = 0;
  REP(d, max_d) {
    while (i < N && A[i] < (d + 1)) {
      i++;
    }
    if (A[i] < d && carry == 0) {
      break;
    }
    auto a = div(A.size() - i + carry, 10);
    ans.push_back(char('0' + a.rem));
    carry = a.quot;
  }
  if (carry != 0) {
    auto carry_str = to_string(carry);
    reverse(ALL(carry_str));
    ans += carry_str;
  }
  reverse(ALL(ans));
  cout << ans << endl;
  return 0;
}
