#include <bits/stdc++.h>

#include <atcoder/all>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N, M, L, S, T;
  cin >> N >> M >> L >> S >> T;

  vector<vector<pair<int, int>>> G(N);
  REP(_, M) {
    int U, V, C;
    cin >> U >> V >> C;
    G[U - 1].emplace_back(V - 1, C);
  }

  set<int> ans;
  stack<tuple<int, int, int>> st;
  st.emplace(0, 0, 0);
  while (!st.empty()) {
    auto [node, sum, cnt] = st.top();
    st.pop();
    for (auto [next, cost] : G[node]) {
      auto t_sum = sum + cost;
      auto t_cnt = cnt + 1;
      if (t_sum > T) {
        continue;
      }
      if (t_cnt == L) {
        if (t_sum >= S) {
          ans.emplace(next + 1);
        }
        continue;
      }
      st.emplace(next, t_sum, t_cnt);
    }
  }
  for (auto a : ans) {
    cout << a << " ";
  }
  cout << endl;
  return 0;
}
