#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N, M;
  cin >> N >> M;
  vector A(M, vector<int>(0));
  REP(i, N) {
    int Ai, Bi;
    cin >> Ai >> Bi;
    Ai--;
    A[Ai].emplace_back(Bi);
  }

  REP(i, M) {
    float sum = 0.F;
    for (auto b : A[i]) {
      sum += b;
    }
    auto ans = sum / A[i].size();
    cout << ans << endl;
  }
  return 0;
}
