#include <bits/stdc++.h>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N;
  cin >> N;

  vector<int> H(N);
  for (auto& h : H) {
    cin >> h;
  }

  int ans = 0;
  int l_max = H.size();
  for (int l = 1; l <= l_max; l++) {
    // begin
    for (int i = 0; i < N; i++) {
      auto tmp = 1;
      auto idx = i + l;
      while (idx < N) {
        if (H[i] == H[idx]) {
          tmp++;
        } else {
          break;
        }
        idx += l;
      }
      ans = max(ans, tmp);
    }
  }
  cout << ans << endl;

  return 0;
}
