#include <bits/stdc++.h>

#include <atcoder/all>

#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int Q;
  cin >> Q;

  REP(_, Q) {
    int N, M, K;
    cin >> N >> M >> K;
    string S;
    cin >> S;

    vector<vector<int>> G(N);
    REP(i, M) {
      int U, V;
      cin >> U >> V;
      --U;
      --V;
      G[U].push_back(V);
    }

    // dp[i][v]: iターン目に頂点vにいるときに手番プレイヤーが勝てるか
    vector dp(K * 2 + 1, vector<bool>(N));
    REP(v, N) { dp[K * 2][v] = (S[v] == 'A'); }

    // 逆順にDP (各K回のターンで、各頂点についてループ)
    for (int i = K * 2 - 1; i >= 0; --i) {
      REP(v, N) {
        dp[i][v] = false;
        for (auto next : G[v]) {
          // 次のターン相手が負ける手なら勝ち
          if (!dp[i + 1][next]) {
            dp[i][v] = true;
          }
        }
      }
    }

    if (dp[0][0]) {
      cout << "Alice" << endl;
    } else {
      cout << "Bob" << endl;
    }
  }

  return 0;
}
