#include <bits/stdc++.h>

#include <atcoder/all>

#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int Q;
  cin >> Q;

  REP(_, Q) {
    int N, M, K;
    cin >> N >> M >> K;
    string S;
    cin >> S;

    vector<int> G(N);
    REP(i, N) {
      int U, V;
      cin >> U >> V;
      --U;
      --V;
      G[U] = V;
    }

    int piece = 0;
    REP(i, K) {
      int turn = 0;
      for (auto node : G) {
        if (turn == K) break;
        node = G[node];
        turn++;
      }
    }

    if (S[piece] == 'A') {
      cout << "Alice" << endl;
    } else {
      cout << "Bob" << endl;
    }
  }

  return 0;
}
