#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N;
  cin >> N;
  vector<int> H(N);
  for (auto& h : H) {
    cin >> h;
  }

  int64_t T = 0;
  for (auto h : H) {
    // T : 3, 6, 9...
    // D : 5, 10, 15 ...
    // T : 2, 5, 7 ...
    // D : 2, 7, 12 ...
    int64_t quot = h / 5;
    T += quot * 3;
    h -= (5 * quot);

    while (h > 0) {
      T++;
      h -= (T % 3 == 0) ? 3 : 1;
    }
  }

  cout << T << endl;

  return 0;
}
