#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N;
  cin >> N;
  vector<int> H(N);
  for (auto& h : H) {
    cin >> h;
  }

  int64_t T = 0;
  for (int i = 0; i < N; i++) {
    auto h = H[i];

    int64_t rem = T % 3;
    // T: 1 2 3
    // D: 1 2 5
    if (rem == 1) {
      h--;
      T++;
      rem++;
      if (h <= 0) {
        continue;
      }
    }
    if (rem == 2) {
      h -= 3;
      T++;
      if (h <= 0) {
        continue;
      }
    }

    // T : 3, 6, 9...
    // D : 5, 10, 15 ...
    auto x = div(h, 5);
    T += x.quot * 3;
    T += (x.rem <= 2) ? x.rem : 3;
  }

  cout << T << endl;

  return 0;
}
