#include <bits/stdc++.h>

#include <atcoder/all>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N;
  cin >> N;

  vector<int> A(N);
  vector<int> B(N);
  REP(i, N) { cin >> A[i] >> B[i]; }

  vector<int> cnts(N);
  REP(i, N) {
    int min_idx = lower_bound(ALL(B), A[i]) - B.begin();
    int max_idx = lower_bound(ALL(B), B[i]) - B.begin();
    cnts[i] = max(0, max_idx - min_idx);
  }

  cout << endl;

  return 0;
}
