#include <bits/stdc++.h>

#include <atcoder/all>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

using namespace atcoder;

using mint = atcoder::modint998244353;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int64_t N;
  cin >> N;
  // All combinations of N numbers with a and b
  auto ans = mint(N + 1) * N / 2;
  // Decrease the multiples of b
  for (int64_t b = 1; b <= N;) {
    auto num_mul = N / b;
    auto next_b = N / num_mul + 1;
    ans -= mint(next_b - b) * num_mul;
    b = next_b;
  }

  cout << ans.val() << "\n";

  return 0;
}
