#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

auto solve(void) {
  int N;
  cin >> N;
  auto p2N = 1<< N;
  vector<int> P(p2N);
  for (auto& p : P) {
    cin >> p;
  }

  for(int w=1; w<p2N; w*=2){
    for(int l=0; l<p2N; l+=w*2){ 
      if(P[l] > P[l+w]){
        REP(i, w){
          swap(P[l+i], P[l+w+i]);
        }
      }
    }
  }
  for(auto p:P){
    cout << p << " ";
  }
  cout << endl;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  int T;
  std::cin >> T;
  REP(t, T) { solve(); }
  return 0;
}
