#include <bits/stdc++.h>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int Q;
  cin >> Q;

  deque<int64_t> dq;
  dq.emplace_back(0);
  for (int q = 0; q < Q; q++) {
    int t;
    cin >> t;
    switch (t) {
      case 1: {
        int64_t l;
        cin >> l;
        dq.emplace_back(dq.back() + l);
      } break;
      case 2: {
        dq.pop_front();
      } break;
      case 3: {
        int k;
        cin >> k;
        k--;
        cout << dq[k] - dq.front() << endl;
      } break;

      default:
        break;
    }
  }

  return 0;
}
