#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int64_t N, M;
  cin >> N >> M;

  vector<int64_t> X(N);
  for (auto& x : X) {
    cin >> x;
  }
  sort(ALL(X));

  vector<int64_t> x_dist(N - 1);
  for (int i = 0; i < N - 1; ++i) {
    x_dist[i] = X[i + 1] - X[i];
  }
  sort(ALL(x_dist));

  int64_t ans = 0;
  int64_t len = x_dist.size() + 1 - M;
  for (int i = 0; i < len; ++i) {
    ans += x_dist[i];
  }

  cout << ans << "\n";

  return 0;
}
