#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N;
  cin >> N;

  vector<int> v(2 * N);
  for (int i = 0; i < 2 * N; i++) {
    cin >> v[i];
  }

  int ans = 0;
  for (int i = 0; i <= (2 * N) - 2; i++) {
    if (v[i] == v[i + 2]) {
      ans++;
    }
  }

  cout << ans << endl;
  return 0;
}
