#include <bits/stdc++.h>

#include <atcoder/all>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)

int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N;
  cin >> N;
  string S;
  cin >> S;

  auto f = [&](const vector<int>& c) -> int64_t {
    // c is the value of A, B, C
    int64_t res = 0;
    // current sum value
    int64_t x = 0;
    // x value -> cnt
    map<int64_t, int> sum;
    REP(i, N) {
      sum[x]++;
      x += c[S[i] - 'A'];
      res += sum[x];
    }
    return res;
  };

  int64_t ans = (N * (N + 1)) / 2;
  // A==B
  ans -= f({1, -1, 0});
  // A==C
  ans -= f({1, 0, -1});
  // B==C
  ans -= f({0, 1, -1});
  const int B = 1e6;
  // A==B, B==C, C==A
  ans += f({B + 1, -B, -1}) * 2;
  cout << ans << endl;

  return 0;
}
