#include <bits/stdc++.h>

#include <atcoder/all>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)

int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N;
  cin >> N;
  string S;
  cin >> S;

  int64_t ans = (N * (N + 1)) / 2;

  int A = 0;
  int B = 0;
  int C = 0;
  int L = 0;
  for (int R = 0; R < N; R++) {
    if (S[R] == 'a') {
      A++;
    } else if (S[R] == 'b') {
      B++;
    } else {
      C++;
    }
    while (L < R && (A == B || B == C || C == A)) {
      if (S[L] == 'a') {
        A--;
      } else if (S[L] == 'b') {
        B--;
      } else {
        C--;
      }
      L++;
    }
  }

  return 0;
}
