#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N, R;
  cin >> N >> R;

  vector<int> L(N);
  REP(i, N) { cin >> L[i]; }

  int l = 0;
  REP(i, N) {
    if (L[i] == 1) {
      l++;
    } else {
      break;
    }
  }

  int r = N - 1;
  while (r > l) {
    if (L[r] == 1) {
      r--;
    } else {
      break;
    }
  }

  if (r < l) {
    cout << 0 << '\n';
    return 0;
  }

  int ans = 0;
  int start = min(l, R);
  int end = max(r, R - 1);
  for (int i = start; i <= end; ++i) {
    if (L[i] == 1) {
      ans += 2;
    } else {
      ans++;
    }
  }

  cout << ans << '\n';
  return 0;
}
