#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

const string YES = "Yes";
const string NO = "No";

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N, M;
  cin >> N >> M;
  vector<bool> T(N);
  for (int i = 0; i < M; i++) {
    int A;
    char B;
    cin >> A >> B;
    A--;
    if (!T[A] && (B == 'M')) {
      cout << "Yes\n";
      T[A] = true;
    } else {
      cout << "No\n";
    }
  }

  return 0;
}
