#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N, M;
  cin >> N >> M;
  unordered_set<char> S;
  REP(_, N) {
    char c;
    cin >> c;
    S.insert(c);
  }
  unordered_set<char> T;
  REP(_, M) {
    char c;
    cin >> c;
    T.insert(c);
  }

  auto judge = [](string& W, unordered_set<char>& us) {
    for (auto w : W) {
      if (!us.contains(w)) {
        return false;
      }
    }
    return true;
  };

  int Q;
  cin >> Q;
  REP(_, Q) {
    string W;
    cin >> W;

    auto isTaKahashi = judge(W, S);
    auto isAoki = judge(W, T);

    if (!(isTaKahashi ^ isAoki)) {
      cout << "Unknown\n";
    } else if (isTaKahashi) {
      cout << "Takahashi\n";
    } else {
      cout << "Aoki\n";
    }
  }
  return 0;
}
