#include <bits/stdc++.h>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  vector<int> arr(5);
  for (auto& a : arr) {
    cin >> a;
  }

  vector<pair<int, string>> V;
  for (int i = 0; i <= 0x1F; i++) {
    int score = 0;
    string str;
    for (int j = 0; j < 5; j++) {
      if (i & (1 << j)) {
        str += ('A' + j);
        score += arr[j];
      }
    }
    V.emplace_back(score, str);
  }
  sort(V.begin(), V.end(), [](auto& p1, auto& p2) {
    if (p1.first != p2.first) {
      return p1.first > p2.first;
    }
    return p1.second < p2.second;
  });
  for (auto v : V) {
    cout << v.second << endl;
  }

  return 0;
}
