#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N;
  cin >> N;

  vector<int> A(N);
  vector<char> S(N);
  for (int i = 0; i < N; i++) {
    cin >> A[i] >> S[i];
  }

  int L = -1;
  int R = -1;
  int ans = 0;
  for (int i = 0; i < N; i++) {
    if (S[i] == 'L') {
      if (L != -1) {
        ans += abs(L - A[i]);
      }
      L = A[i];
    } else if (S[i] == 'R') {
      if (R != -1) {
        ans += abs(R - A[i]);
      }
      R = A[i];
    }
  }

  cout << ans << endl;

  return 0;
}
