#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int64_t N, K, X;
  cin >> N >> K >> X;

  vector<int64_t> A(N);
  REP(i, N) { cin >> A[i]; }
  sort(ALL(A));

  int64_t ans = N - K;  // All waters
  int64_t sake = 0;
  REP(i, K) {
    sake += A[i];
    ans++;
    if (sake >= X) {
      cout << ans << endl;
      return 0;
    }
  }

  cout << -1 << endl;
  return 0;
}
