#include <bits/stdc++.h>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N, M;
  cin >> N >> M;

  vector<pair<int, int>> P(M);

  for (auto& p : P) {
    cin >> p.first;
  }
  for (auto& p : P) {
    cin >> p.second;
  }
  sort(P.begin(), P.end());
  P.emplace_back(N + 1, 0);

  int x_prev = 0;
  int64_t moves = 0;
  int64_t stones = 1;
  for (auto [x, a] : P) {
    // ckeck the previous section can be filfilled by stone;
    auto dist = x - x_prev;
    auto carry = stones - dist;
    if (carry < 0) {
      cout << -1 << endl;
      return 0;
    }

    // count unnecessary move num
    moves += static_cast<int64_t>(x) * a;

    x_prev = x;
    stones = carry + a;
  }

  // check remain stones are none
  if (stones != 0) {
    cout << -1 << endl;
    return 0;
  }

  auto ans = static_cast<int64_t>(N + 1) * N / 2 - moves;
  cout << ans << endl;

  return 0;
}
