#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  int64_t N;
  cin >> N;
  vector<int> A(N);
  REP(i, N) { cin >> A[i]; }
  sort(ALL(A));
  int idx = 0;
  int cnt = N;
  int ans = 0;
  for (int i = 0; i <= 100; i++) {
    while (A[idx] < i) {
      idx++;
      cnt--;
      if (idx >= N) {
        break;
      }
    }
    if (cnt < 0) {
      break;
    }
    if (cnt >= i) {
      ans = i;
    }
  }
  cout << ans << endl;
  return 0;
}
