#include <bits/stdc++.h>
using namespace std;

const string YES = "Yes";
const string NO = "No";

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  string S;
  cin >> S;

  auto isInclude = [&](char c) { return S.find(c) != string::npos; };

  auto includeA = isInclude('A');
  auto includeB = isInclude('B');
  auto includeC = isInclude('C');

  if (includeA && includeB && includeC) {
    cout << YES << endl;
  } else {
    cout << NO << endl;
  }

  return 0;
}
