#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

void chmin(int& x, int y) { x = min(x, y); }

int64_t solve(int64_t a, std::string b) {
  vector<vector<int>> dp(b.size(), vector<int>(2, 1));
  REP(i, b.size()) { dp[i][b[i] - '0'] = 0; }
  while (dp.size() > 1) {
    vector<vector<int>> old(dp.size() / 3, vector<int>(2, INT32_MAX));
    swap(dp, old);
    for (int l = 0; l < old.size(); l += 3) {
      // Loop all permutations (2^3)
      REP(s, 1 << 3) {
        int cost = 0;
        REP(i, 3) { cost += old[l + i][s >> i & 1]; }
        int x = (popcount(static_cast<uint32_t>(s)) >= 2) ? 1 : 0;
        chmin(dp[l / 3][x], cost);
      }
    }
  }

  // The cost before value change is 0
  return max(dp[0][0], dp[0][1]);
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  int64_t a;
  std::string b;
  std::cin >> a >> b;
  auto ans = solve(a, b);
  std::cout << ans << '\n';
  return 0;
}
