#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N, K;
  cin >> N >> K;
  vector<int64_t> A(N);
  REP(i, N) { cin >> A[i]; }

  // value -> sum
  unordered_map<int64_t, int64_t> mp;
  REP(i, N) { mp[A[i]] += A[i]; }

  // sum -> value
  set<pair<int64_t, int64_t>> st;
  for (auto& [key, sum] : mp) {
    st.emplace(sum, key);
  }

  REP(i, K) {
    if (st.empty()) {
      break;
    }
    auto it = *st.rbegin();
    st.erase(it);
    mp[it.second] = 0;
  }

  int64_t ans = 0;
  for (auto& [_, sum] : mp) {
    ans += sum;
  }

  cout << ans << endl;

  return 0;
}
