#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N, K;
  cin >> N >> K;
  vector<int64_t> A(N);
  REP(i, N) { cin >> A[i]; }

  // value -> cnt
  map<int64_t, int64_t> mp;
  REP(i, N) { mp[A[i]]++; }

  int64_t ans = 0;
  vector<int64_t> sum;
  for (auto& [key, cnt] : mp) {
    auto x = key * cnt;
    sum.push_back(x);
    ans += x;
  }
  sort(ALL(sum));

  REP(i, K) {
    if (sum.empty()) {
      break;
    }
    auto it = *sum.rbegin();
    sum.pop_back();
    ans -= it;
  }
  cout << ans << endl;

  return 0;
}
