#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

int64_t solve(int n, const std::vector<int64_t> &a, const std::vector<int64_t> &b) {
  int64_t a_sum = 0;
  REP(i, n) { a_sum += a[i]; }
  int64_t b_sum = 0;
  REP(i, n) { b_sum += b[i]; }
  return a_sum - b_sum + 1;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  constexpr int n = 9;
  std::vector<int64_t> a(n);
  REP(i, n) { std::cin >> a[i]; }
  std::vector<int64_t> b(n);
  REP(i, n) { std::cin >> b[i]; }
  auto ans = solve(n, a, b);
  std::cout << ans << '\n';
  return 0;
}
