#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

void solve(void) {
  int N, M;
  cin >> N >> M;
  vector<int> A(N);
  for (auto& a : A) {
    cin >> a;
  }
  sort(ALL(A));
  vector<int> B(N);
  for (auto& b : B) {
    cin >> b;
  }
  sort(ALL(B));
  reverse(ALL(B));

  int ans = 0;
  int i = 0;
  vector<bool> used(N, false);
  bool loop = false;
  for (int j = 0; j < N; ++j) {
    while (!loop) {
      auto mod = (A[i] + B[j]) >= M;
      if (mod) {
        break;
      }
      i++;
      if (i >= N) {
        loop = true;
        i = 0;
        break;
      }
    }

    while (used[i]) {
      i++;
    }
    auto mod = (A[i] + B[j]) % M;
    ans += mod;
    used[i] = true;
    i++;
  }

  cout << ans << "\n";
}

struct Present {
  int P;
  int A;
  int B;
};

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N;
  cin >> N;
  vector<Present> presents(N);
  REP(i, N) { cin >> presents[i].P >> presents[i].A >> presents[i].B; }

  vector<unordered_map<int, int>> cache(N);
  int64_t Q;
  cin >> Q;
  REP(q, Q) {
    int X;
    cin >> X;
    vector<int> tmp(N);
    bool found = false;
    REP(i, N) {
      if (presents[i].P >= X) {
        X += presents[i].A;
      } else {
        X = max(X - presents[i].B, 0);
      }
      if (cache[i].contains(X)) {
        found = true;
        auto ans = cache[i][X];
        cout << ans << '\n';
        REP(j, i) { cache[j][tmp[j]] = ans; }
        break;
      }
      tmp[i] = X;
    }
    if (!found) {
      cout << X << '\n';
      REP(i, N) { cache[i][tmp[i]] = X; }
    }
  }
  return 0;
}
