#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

struct Present {
  int P;
  int A;
  int B;
};

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N;
  cin >> N;
  vector<Present> presents(N);
  REP(i, N) { cin >> presents[i].P >> presents[i].A >> presents[i].B; }
  vector<int> B_sum(N + 1);
  REP(i, N) { B_sum[i + 1] = B_sum[i] + presents[i].B; }

  int SIZE = 1001;
  vector<vector<int>> table(N + 1, vector<int>(SIZE));
  REP(i, SIZE) { table[N][i] = i; }
  REP(i, N) {
    auto idx = N - i - 1;
    REP(j, SIZE) {
      int next_j;
      auto [P, A, B] = presents[idx];
      if (P >= j) {
        next_j = j + A;
      } else {
        next_j = max(0, j - B);
      }
      table[idx][j] = table[idx + 1][next_j];
    }
  }

  int64_t Q;
  cin >> Q;
  REP(q, Q) {
    int X;
    cin >> X;

    int idx = 0;
    if (X >= SIZE) {
      auto it = upper_bound(ALL(B_sum), X - SIZE);
      if (it == B_sum.end()) {
        cout << X - B_sum[N] << '\n';
        continue;
      }
      idx = it - B_sum.begin();
      X -= B_sum[idx];
    }
    cout << table[idx][X] << '\n';
  }
  return 0;
}
