#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int Q;
  cin >> Q;
  vector<int> X;
  REP(i, Q) {
    int q;
    cin >> q;
    switch (q) {
      case 1: {
        int x;
        cin >> x;
        X.push_back(x);
      } break;
      case 2: {
        sort(ALL(X));
        reverse(ALL(X));
        cout << X.back() << '\n';
        X.pop_back();
      } break;
      default:
        break;
    }
  }
  return 0;
}
