#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  int Q;
  std::cin >> Q;
  std::stack<int64_t> st;
  for (int i = 0; i < 100; i++) {
    st.emplace(0);
  }
  REP(i, Q) {
    int q;
    std::cin >> q;
    switch (q) {
      case 1: {
        int x;
        cin >> x;
        st.emplace(x);
      } break;
      case 2: {
        auto value = st.top();
        st.pop();
        cout << value << "\n";
      } break;
      default:
        break;
    }
  }
  return 0;
}
