#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N, M;
  cin >> N >> M;
  unordered_map<int, unordered_set<int>> A;
  int ans = 0;
  int R, C;
  REP(_, M) {
    cin >> R >> C;
    if (A[R - 1].contains(C - 1) || A[R].contains(C - 1) || A[R - 1].contains(C) || A[R].contains(C)) {
      continue;
    }
    A[R - 1].insert(C - 1);
    A[R - 1].insert(C);
    A[R].insert(C - 1);
    A[R].insert(C);
    ans++;
  }
  cout << ans << endl;

  return 0;
}
