#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N, K, M;
  cin >> N >> K >> M;
  vector<pair<int64_t, int64_t>> VC(N);
  REP(i, N) cin >> VC[i].second >> VC[i].first;
  sort(ALL(VC));
  reverse(ALL(VC));

  vector<bool> color(N, false);
  int64_t colors = 0;
  int64_t cnt = 0;
  int64_t ans = 0;
  REP(i, N) {
    auto rem = K - cnt;
    auto req = M - colors;

    if (rem <= 0) break;
    auto [v, c] = VC[i];

    if (rem == req) {
      // required new kind
      if (!color[c - 1]) {
        ans += v;
        cnt++;
        color[c - 1] = true;
        colors++;
      }
    } else {
      // not required new kind
      ans += v;
      cnt++;
      if (!color[c - 1]) {
        color[c - 1] = true;
        colors++;
      }
    }
  }
  cout << ans << endl;

  return 0;
}
