#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N, K, M;
  cin >> N >> K >> M;
  vector<vector<int64_t>> VS(N);
  REP(i, N) {
    int64_t c, v;
    cin >> c >> v;
    VS[c - 1].push_back(v);
  }

  // sapalate juels
  // top: top value in color
  // other: other values
  vector<int> top, other;
  REP(i, N) {
    if (VS[i].empty()) continue;
    sort(ALL(VS[i]));
    top.push_back(VS[i].back());
    VS[i].pop_back();
    other.insert(other.end(), ALL(VS[i]));
  }

  // select top M kinds
  int64_t ans = 0;
  sort(top.begin(), top.end());
  REP(i, M) {
    ans += top.back();
    top.pop_back();
  }
  // insert remaining top to other
  other.insert(other.end(), ALL(top));
  sort(other.begin(), other.end());
  // select remaining juels
  REP(i, K - M) {
    ans += other.back();
    other.pop_back();
  }
  cout << ans << endl;

  return 0;
}
