#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N;
  cin >> N;
  vector A(N, vector<int>(N));
  int r = 0;
  int c = (N - 1) / 2;
  A[r][c] = 1;
  REP(_, N * N - 1) {
    auto tmp_r = (r - 1 + N) % N;
    auto tmp_c = (c + 1) % N;
    if (A[tmp_r][tmp_c] == 0) {
      A[tmp_r][tmp_c] = A[r][c] + 1;
      r = tmp_r;
      c = tmp_c;
    } else {
      tmp_r = (r + 1) % N;
      A[tmp_r][c] = A[r][c] + 1;
      r = tmp_r;
    }
  }

  REP(i, N) {
    REP(j, N) {
      cout << A[i][j];
      if (j != N - 1) {
        cout << " ";
      }
    }
    cout << "\n";
  }
  return 0;
}
