#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  // failed to analyze input format
  // TODO: edit here
  int n, q;
  std::cin >> n >> q;

  std::vector<int> a(n);
  REP(i, n) { a[i] = i; }
  std::vector<int> nest(n);
  REP(i, n) { nest[a[i]]++; }
  std::vector<int> nest_sorted(n);
  REP(i, n) { nest_sorted[i] = nest[i]; }

  REP(i, q) {
    int query;
    cin >> query;
    switch (query) {
      case 1: {
        int P, H;
        cin >> P >> H;

        P--;
        H--;

        auto it_dec = lower_bound(nest_sorted.begin(), nest_sorted.end(), nest[a[P]]);
        (*it_dec)--;
        nest[a[P]]--;

        a[P] = H;
        auto it_inc = upper_bound(nest_sorted.begin(), nest_sorted.end(), nest[a[P]]);
        (*(it_inc - 1))++;
        nest[a[P]]++;
      } break;

      default: {
        // sort(nest_sorted.begin(), nest_sorted.end());
        auto it = lower_bound(nest_sorted.begin(), nest_sorted.end(), 2);
        auto count = distance(it, nest_sorted.end());
        std::cout << count << std::endl;
      } break;
    }
  }
  return 0;
}
