#include <bits/stdc++.h>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N;

  cin >> N;

  string s = to_string(N);

  cout << s[1] << s[2] << s[0] << " " << s[2] << s[0] << s[1] << endl;

  return 0;
}
