#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

struct Parts {
  int W;
  int H;
  int B;
};

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N;
  cin >> N;

  vector<Parts> P(N);
  REP(i, N) {
    int w, h, b;
    cin >> w >> h >> b;
    P[i] = {w, h, b};
  }
  sort(ALL(P));

  int64_t total_B = 0;
  int64_t total_H = 0;
  int64_t ans = 0;
  for (const auto& p : P) {
    if (p.B >= p.H) {
      ans += p.W;
      total_B += p.B;
    }
  }

  return 0;
}
