#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

struct Parts {
  int W;
  int H;
  int B;
};

struct Cost {
  int W;
  int diff;
};

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N;
  cin >> N;

  int64_t total_W = 0;
  int64_t total_B = 0;
  vector<Parts> P(N);
  vector<Cost> C;
  REP(i, N) {
    int w, h, b;
    cin >> w >> h >> b;
    P[i] = {w, h, b};
    total_W += w;
    total_B += b;
    if (h > b) {
      C.emplace_back(w, h - b);
    }
  }

  auto max_W = total_W / 2;
  auto size = C.size();
  // dp
  // j: total weight
  vector<int64_t> dp(max_W + 1);
  dp[0] = 0;
  // Iterate parts
  REP(i, size) {
    vector<int64_t> prev_dp(max_W + 1);
    swap(prev_dp, dp);
    auto [w, diff] = C[i];
    REP(j, max_W + 1) {
      // not use parts as head
      dp[j] = max(prev_dp[j], dp[j]);
      if (j + w <= max_W) {
        // use parts as head
        dp[j + w] = max(prev_dp[j + w], prev_dp[j] + diff);
      }
    }
  }

  cout << dp[max_W] + total_B << endl;

  return 0;
}
