#include <bits/stdc++.h>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  string S;
  cin >> S;

  auto solve = [&](auto K) {
    auto d = div(K, S.size());
    d.quot;
    d.rem;
  };

  int Q;
  cin >> Q;
  for (int i = 0; i < Q; i++) {
    int64_t K;
    cin >> K;
    cout << solve(K) << " ";
  }
  cout << endl;

  return 0;
}
