#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
  int N;
  cin >> N;

  vector<vector<int>> A(N, vector<int>(N));
  for (int i = 0; i < N; i++) {
    for (int j = 0; j <= i; j++) {
      int a;
      cin >> a;
      a--;
      A[i][j] = a;
    }
  }

  int alc = 0;
  for (int i = 0; i < N; i++) {
    if (alc >= i) {
      alc = A[alc][i];
    } else {
      alc = A[i][alc];
    }
  }

  alc++;
  cout << alc << endl;

  return 0;
}
