#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int N;
  cin >> N;
  vector<int> A(N);
  REP(i, N) { cin >> A[i]; }

  vector<int> v;
  REP(i, N) {
    auto a = A[i];
    int ans = -1;
    for (int j = i - 1; j >= 0; --j) {
      if (v[j] > a) {
        ans = j + 1;
        break;
      }
    }
    cout << ans << endl;
    v.emplace_back(a);
  }

  return 0;
}
