name: Validate source branch for main

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if source branch is feature/**
        run: |
          echo "Source branch: ${{ github.head_ref }}"
          if [[ ! "${{ github.head_ref }}" =~ ^feature/.* ]]; then
            echo "❌ Error: Only branches starting with 'feature/' can be merged into main."
            exit 1
          fi
