#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);

  int64_t N, L;
  std::cin >> N >> L;
  vector<int64_t> Pi_cnt(L);
  int64_t Pi = 0;
  Pi_cnt[0]++;
  REP(i, N - 1) {
    int64_t di;
    cin >> di;
    Pi = (Pi + di) % L;
    Pi_cnt[Pi]++;
  }

  if (L % 3 != 0) {
    cout << 0 << endl;
    return 0;
  }

  int64_t ans = 0;
  const int64_t len = L / 3;
  REP(i, len) {
    const auto P1 = i;
    const auto P2 = (P1 + len) % L;
    const auto P3 = (P2 + len) % L;
    ans += Pi_cnt[P1] * Pi_cnt[P2] * Pi_cnt[P3];
  }
  cout << ans << endl;

  return 0;
}
