#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

const std::string YES = "Yes";
const std::string NO = "No";
auto solve(int N, int64_t W, const std::vector<int64_t> &X, const std::vector<int64_t> &Y, int Q,
           const std::vector<int64_t> &T, const std::vector<int64_t> &A) {
  // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  int N;
  int64_t W;
  int Q;
  std::cin >> N;
  std::vector<int64_t> X(N), Y(N);
  std::cin >> W;
  REP(i, N) { std::cin >> X[i] >> Y[i]; }
  std::cin >> Q;
  std::vector<int64_t> T(Q), A(Q);
  REP(i, Q) { std::cin >> T[i] >> A[i]; }
  auto ans = solve(N, W, X, Y, Q, T, A);
  REP(i, Q) { std::cout << a[i] << '\n'; }
  return 0;
}
